
CREATE LANGUAGE plpgsql;


DROP TYPE IF EXISTS sex CASCADE;
CREATE TYPE sex AS ENUM ('M','F');

DROP TYPE IF EXISTS sport CASCADE;
CREATE TYPE sport AS ENUM ('Basket-Ball','Cyclisme','Football','Rugby','Sports d''Hiver','Tennis');

DROP TABLE IF EXISTS Accounts CASCADE ;
CREATE TABLE Accounts ( id SERIAL PRIMARY KEY,
						login VARCHAR(20) UNIQUE NOT NULL,
						password VARCHAR(40) NOT NULL,
						email VARCHAR(40) UNIQUE NOT NULL,
						sex sex NULL,
						years INTEGER CHECK((years <= 2010 AND years >= 1930) OR years = NULL),
						months INTEGER CHECK((months >= 1 AND months <= 12) OR months = NULL),
						days INTEGER CHECK((days >= 1 AND days <= 31) OR days = NULL),
						nationality VARCHAR(40) NULL,
						sport sport NOT NULL,
						fan VARCHAR(20) NULL,
						newsletter BOOLEAN NOT NULL,
						ip VARCHAR(16) NOT NULL,
						ban_time TIMESTAMP NULL,
						register_date TIMESTAMP NOT NULL,
						last_connection TIMESTAMP NOT NULL,
						accesslevel INTEGER CHECK( accesslevel >= 0 AND accesslevel <= 100 ) NOT NULL,
						CONSTRAINT check_email CHECK (((email)::text ~~ '%@%.%'::text))
					);
					
DROP TABLE IF EXISTS LoginLog CASCADE;
CREATE TABLE LoginLog ( id SERIAL PRIMARY KEY,
						log_time TIMESTAMP NOT NULL,
						ip VARCHAR(16) NOT NULL,
						login VARCHAR(20) NOT NULL,
						password VARCHAR(40) NOT NULL,
						account_exist BOOLEAN NOT NULL,
						right_password BOOLEAN NULL);
						
DROP TABLE IF EXISTS Connected CASCADE;
CREATE TABLE Connected ( id SERIAL PRIMARY KEY,
						 ip VARCHAR(16) UNIQUE NOT NULL,
						 connect_time TIMESTAMP NOT NULL);
						 
						 
DROP TABLE IF EXISTS Questionnaires CASCADE;
CREATE TABLE Questionnaires (	id SERIAL PRIMARY KEY,
								sport sport NOT NULL );
								
								
DROP TABLE IF EXISTS Questions CASCADE;
CREATE TABLE Questions ( id SERIAL PRIMARY KEY,
						 id_questionnaire INTEGER NULL REFERENCES Questionnaires(id),
						 question text UNIQUE NOT NULL,
						 answer text NOT NULL,
						 sport sport NOT NULL);
						 
						 
DROP TABLE IF EXISTS Scores CASCADE;
CREATE TABLE Scores (	id SERIAL PRIMARY KEY,
						id_account INTEGER NOT NULL REFERENCES Accounts( id ),
						id_questionnaire INTEGER NOT NULL REFERENCES Questionnaires( id ),
						score INTEGER NOT NULL CHECK( score >= 0 AND score <= 500),
						start_time TIMESTAMP NOT NULL,
						finish_time TIMESTAMP NOT NULL,
						score_details INTEGER[5] NOT NULL 
							CHECK   (	score_details[0] >= 0 AND score_details[1] >= 0 AND score_details[2] >= 0 AND score_details[3] >= 0 AND 
										score_details[4] >= 0 AND score_details[0] <=100	AND score_details[1] <=100	AND score_details[2] <=100	AND 
										score_details[3] <=100	AND score_details[4] <=100	
									)
					);
					
					
DROP TABLE IF EXISTS Programming CASCADE;
CREATE TABLE Programming 	( 	id SERIAL PRIMARY KEY,
								week date UNIQUE NOT NULL,
								BasketBall INTEGER NOT NULL REFERENCES Questionnaires (id),
								Cyclisme INTEGER NOT NULL REFERENCES Questionnaires (id),
								Football INTEGER NOT NULL REFERENCES Questionnaires (id),
								Rugby INTEGER NOT NULL REFERENCES Questionnaires (id),
								SportsHiver INTEGER NOT NULL REFERENCES Questionnaires (id),
								Tennis INTEGER NOT NULL REFERENCES Questionnaires (id)
							);

							
CREATE FUNCTION check_sport() RETURNS trigger AS $if_sport$
    BEGIN
        
        IF (SELECT COUNT(*) != 1 FROM Questionnaires WHERE id = NEW.BasketBall AND sport = 'Basket-Ball') THEN
			RAISE EXCEPTION 'sport Basket-Ball incompatible';
        END IF;
		
		IF (SELECT COUNT(*) != 1 FROM Questionnaires WHERE id = NEW.Cyclisme AND sport = 'Cyclisme') THEN
           RAISE EXCEPTION 'sport Cyclisme incompatible';
        END IF;
		
		IF (SELECT COUNT(*) != 1 FROM Questionnaires WHERE id = NEW.Football AND sport = 'Football') THEN
            RAISE EXCEPTION 'sport Football incompatible';
        END IF;
		
		IF (SELECT COUNT(*) != 1 FROM Questionnaires WHERE id = NEW.Rugby AND sport = 'Rugby') THEN
            RAISE EXCEPTION 'sport Rugby incompatible';
        END IF;
		
		IF (SELECT COUNT(*) != 1 FROM Questionnaires WHERE id = NEW.SportsHiver AND sport = 'Sports d''Hiver') THEN
            RAISE EXCEPTION 'sport Sports d''Hiver incompatible';
        END IF;
		
		IF (SELECT COUNT(*) != 1 FROM Questionnaires WHERE id = NEW.Tennis AND sport = 'Tennis') THEN
            RAISE EXCEPTION 'sport Tennis incompatible';
        END IF;
		
        RETURN NEW;
    END;
$if_sport$ LANGUAGE plpgsql;


CREATE TRIGGER if_sport 
	BEFORE INSERT OR UPDATE ON Programming FOR EACH ROW
	EXECUTE PROCEDURE check_sport();


DROP TABLE IF EXISTS CustomAnswer CASCADE;
CREATE TABLE CustomAnswer ( id SERIAL PRIMARY KEY,
							 answer text UNIQUE NOT NULL,
							 good BOOLEAN NOT NULL,
							 sport sport NOT NULL);
							 
DROP TABLE IF EXISTS News CASCADE;
CREATE TABLE News (	id SERIAL PRIMARY KEY,
					title VARCHAR(200) NOT NULL,
					author VARCHAR(20) REFERENCES Accounts(login),
					content TEXT NOT NULL,
					write_date TIMESTAMP NOT NULL);

	
------------------------------------------------------------------ INSERT VALUES ------------------------------------------------------------------


SET client_encoding TO 'LATIN1';


INSERT INTO questions (id,question,answer,sport) VALUES (DEFAULT, 'Quel est le premier français a figuré sur la liste définitive du ballon d''or 2009 ?', 'henry', 'Football'),
(DEFAULT, 'Révélation de la Bundesliga, j''inscris pas moins de 26 buts avec Wolsburg, qui suis-je ?', 'dzeko', 'Football'),
(DEFAULT, 'Après avoir quitté Lyon, dans quel club évolue Juninho Pernambucano ?', 'Doha', 'Football'),
(DEFAULT, 'A défaut de temps de jeu à l''Internazionale, dans quel club évolue depuis l''été 2009, Adriano ?', 'flamengo', 'Football'),
(DEFAULT, 'Combien de français compte l''effectif du  Real Madrid en fin d''année 2009 ?', '2', 'Football'),
(DEFAULT, 'En 2009, combien de millions d''euros a versé le Real de Madrid pour se payer les services de C.Ronaldo ?', '94', 'Football'),
(DEFAULT, 'Suite à une visite médicale révélant un problème cardiaque, ma carrière et mon transfert à l''AS Monaco sont suspendus, qui suis-je ?', 'savidan', 'Football'),
(DEFAULT, 'Formé à Metz, et aujourd''hui à Manchester City, je suis considéré avec Samuel Eto''o comme l''un des meilleurs attaquants africains au monde, qui suis je ?', 'adebayor', 'Football'),
(DEFAULT, 'Quel club a remporté pour la deuxième année consécutive le championnat russe ?', 'rubin kazan', 'Football'),
(DEFAULT, 'Combien d''équipes participeront à la phase finale de la Coupe du Monde 2010 ? ', '32', 'Football'),
(DEFAULT, 'Combien de français figurent dans la liste des 30 derniers joueurs du Ballon d''Or 2009 ?', '4', 'Football'),
(DEFAULT, 'Ancien milieu défensif irlandais, je suis limogé du poste d''entraineur de Sunderland, qui suis-je ?', 'keane', 'Football'),
(DEFAULT, 'Ballon d''or 2009, complétez :
1: Messi
2: C.Ronaldo
3: Xavi
4: ?', 'iniesta', 'Football'),
(DEFAULT, 'Quel ancien joueur déclare, fin novembre 2009 : " Domenech, c''est le plus mauvais entraineur depuis Louis 16 ! (...) " ? ', 'cantona', 'Football'),
(DEFAULT, 'Joueur mythique de Boca Junior, je reviens en sélection et marque un but important lors des qualifications pour la Coupe du Monde, qui suis-je ? ', 'palermo', 'Football'),
(DEFAULT, 'Défenseur international français, je raccroche les crampons en milieu d''année 2009 suite à une terrible blessure au tendon d''Achille, qui suis-je ?', 'sagnol', 'Football'),
(DEFAULT, 'Transféré durant l''été 2009 du Werder de Brême, je gagne petit à petit le cœur des supporters de la Vieille Dame, qui suis-je ?', 'diego', 'Football'),
(DEFAULT, 'Transféré durant l''été 2009 du Genoa, je forme avec Samuel Eto''o, l''attaque explosive de l''Inter de Milan, qui suis-je ?', 'milito', 'Football'),
(DEFAULT, 'Jeune Nigérian, transféré de Newcastle à Wolsburg après avoir passé une saison noire avec les Black Catz, qui suis-je ? ', 'martins', 'Football'),
(DEFAULT, 'Milieu de terrain hollandais, ayant évolué à Bordeaux, à l''Atletico Madrid. J''ai été mis a l''essai par le FC METZ, mais finalement non conservé, qui suis-je ?', 'musampa', 'Football'),
(DEFAULT, 'Transféré de l''Ajax durant le mercato d''été 2009, je forme aujourd''hui la charnière centrale avec William GALLAS à Arsenal, qui suis-je ?', 'vermaelen', 'Football'),
(DEFAULT, 'Dans quel club évolue, en 2009, Damian DUFF ?', 'fulham', 'Football'),
(DEFAULT, 'Quel club brésilien, a pour but le recrutement de l''ancien parisien Ronaldinho pour la saison 2010/2011 ?', 'corinthians', 'Football'),
(DEFAULT, 'Milieu belge d''Everton, je surprends par ma coupe de cheveux mais surtout pour mon talent, qui suis-je ?', 'fellaini', 'Football'),
(DEFAULT, 'Quel joueur fantasque, a inscrit un quintuplé et figure au 1er décembre 2009, comme le meilleur buteur de la Premier League ?', 'defoe', 'Football'),
(DEFAULT, 'Quelle star du rugby a fait un retour remarqué au sein du petit club de Marseille-Vitrolles ?', 'Lomu', 'Rugby'),
(DEFAULT, 'Attaquant français, je quitte Sunderland pour le Panathinaikos durant l''été 2009, qui suis-je ?', 'cisse', 'Football'),
(DEFAULT, 'Attaquant brésilien, je retrouve les terrains avec Arsenal, après une très longue blessure, qui suis-je ?', 'eduardo', 'Football'),
(DEFAULT, 'Dans la course au Ballon d''or, combien de points ont séparé Lionel Messi de son dauphin, C.Ronaldo ?', '240', 'Football'),
(DEFAULT, 'Quel club anglais est surnommé le "deuxième Chelsea" après un recrutement digne des plus grands ?', 'manchester city', 'Football'),
(DEFAULT, 'Irlandais considéré comme l''un des meilleurs passeurs de Premier League, mes rapports houleux avec l''entraineur ne me permettent pas d''intégrer l''effectif pour les qualifications à la Coupe du Monde 2010, qui suis-je ?', 'ireland', 'Football'),
(DEFAULT, 'Quelle équipe, n''ayant plus participé à la Coupe du Monde depuis 1985, sera de la partie en Afrique du Sud ?', 'algérie', 'Football'),
(DEFAULT, 'Quel ancien entraineur de la Squadra Azzura, a pris les rênes du Racing Métro ?', 'Berbizier', 'Rugby'),
(DEFAULT, 'Flanker prometteur du Clermont-Auvergne, je fête ma première sélection, à l''âge de 20 ans, contre les Samoa. Je suis... ', 'Lapandry', 'Rugby'),
(DEFAULT, 'Je suis un entraineur australien limogé par Guazzini après un début de saison 2009 catastrophique avec le Stade Français. Je suis...', 'McKenzie', 'Rugby'),
(DEFAULT, 'Véritable poutre en mêlée, et d''une puissance rare, je suis avec mes 138kg un joueur à part entière du Stade Toulousain. Je suis...', 'Census Johnston', 'Rugby'),
(DEFAULT, 'Capitaine émérite de Toulon, je suis désigné meilleur troisième ligne centre du Top 14, lors de la saison 2008-2009. Je suis...', 'Van Niekerk', 'Rugby'),
(DEFAULT, 'Je suis un joueur néo-zélandais, ancienne star du XIII, aujourd''hui Centre à XV, et ayant remporté un match de Boxe professionnel. Je suis... ', 'Sony Bill Williams', 'Rugby'),
(DEFAULT, 'Quel jeune ouvreur argentin du Stade Français, a joué à Perpignan et à Leicester ?', 'Mieres', 'Rugby'),
(DEFAULT, 'Quel International français s''est exilé outre Manche pendant une saison, avant de faire son retour dans son club formateur, le Stade Français ?', 'Kayser', 'Rugby'),
(DEFAULT, 'Quel ancien talonneur international est l''entraineur des avants du Stade Toulousain, pour la saison 2009-2010 ?', 'Bru', 'Rugby'),
(DEFAULT, 'Quel arrière, pouvant aussi joué ouvreur, a rejoint le Racing Métro après avoir réussi quelques jolis drops avec Montauban ?', 'Fortassin', 'Rugby'),
(DEFAULT, 'En Mars 2009, quel joueur du Top 14 a battu le record du plus grand nombre de coups de pieds consécutifs réussis ?', 'Brock James', 'Rugby'),
(DEFAULT, 'Quel club, en 2009, est considéré comme le club le plus riche au monde ?', 'manchester united', 'Football'),
(DEFAULT, 'Formé au FC METZ, je me révèle au grand public avec l''Olympique Lyonnais en fin d''année 2009, qui suis-je ?', 'pjanic', 'Football'),
(DEFAULT, 'Conscient de la difficulté de jouer en équipe de France, je prends la nationalité polonaise, en 2009, et inscrit deux buts pour mon premier match, qui suis-je ?', 'obraniak', 'Football'),
(DEFAULT, 'Famille de biathlètes, chefs de file de l''équipe de France de Biathlon. Nous enchainons les podiums en 2009. Nous sommes les...', 'Fourcade', 'Sports d''Hiver'),
(DEFAULT, 'Quel ancien treiziste australien, aujourd''hui converti au XV, s''impose match après match au poste d''ouvreur avec la Squadra Azzura ?', 'Gower', 'Rugby'),
(DEFAULT, 'Rugbyman camerounais au physique impressionnant, passé par Auch et le Stade Français, ayant gagné, à la surprise générale, une place de titulaire à l''USAP. Je suis... ', 'Tchale-Watchou', 'Rugby'),
(DEFAULT, 'Capitaine polyvalent de l''équipe briviste. Je suis un ancien treiziste pouvant couvrir tous les postes du 10 au 15. Je suis...', 'Estebanez', 'Rugby'),
(DEFAULT, 'Après avoir entrainé Montauban, j''ai pris en 2009, la tête du Castres Olympique avec Laurent Travers. Je suis...', 'Labit', 'Rugby'),
(DEFAULT, 'Entraineur français ayant remplacé au pied levé C.Dominici pour entrainer les lignes arrières du Stade Français, à l''orée de la saison 2009. Je suis...', 'Faugeron', 'Rugby'),
(DEFAULT, 'Perpignanais pure souche, je marque l''essai de la victoire en finale du Top 14 saison 2008/2009 contre l''ASM.', 'Marty', 'Rugby'),
(DEFAULT, 'Ailier américain, véritable feu follet, je suis capable de courir le 100m en 10 sec. et 25 centièmes, et j''enchante le Top 14 à chacun de mes essais. Je suis...', 'Ngwenya', 'Rugby'),
(DEFAULT, 'Pilier sur le terrain, tout comme dans le vestiaire, je signe dans mon club de cœur après 6 saisons au Clermont Auvergne.', 'Emmanuelli', 'Rugby'),
(DEFAULT, 'Course de Biathlon, signifiant étymologiquement "départ en ligne". Je mets au prise les trente premiers du classement général. Je suis la...', 'Mass-Start', 'Sports d''Hiver'),
(DEFAULT, 'Biathlète suédoise, aussi rapide à ski qu''habile au tir, je remporte le gros globe de Cristal durant la saison 2008/2009.', 'Jonsson', 'Sports d''Hiver'),
(DEFAULT, 'Jeune et talentueuse biathlète allemande, j''ai connu une saison difficile en 2008/09, après avoir survolé la saison précédente.', 'Neuner', 'Sports d''Hiver'),
(DEFAULT, 'Biathlète polonais, très adroit au tir, je termine la saison 2008/09  à la deuxième place du classement général.', 'Sikora', 'Sports d''Hiver'),
(DEFAULT, 'Biathlète italienne, je suis plus connue pour être la femme du champion Bjoerndalen, que pour mes performances.', 'Santer', 'Sports d''Hiver'),
(DEFAULT, 'Biathlète suisse, qui a créé la surprise fin d''année 2009, en accrochant un podium inespéré en Sprint. Je suis...', 'Frei', 'Sports d''Hiver'),
(DEFAULT, 'Biathlète français qui, par sa régularité au tir, remporte le seul succès français en 2008/09.', 'Jay', 'Sports d''Hiver'),
(DEFAULT, 'Biathlète suédois, souvent placé mais rarement gagnant, ses 6ème, 7ème et 9ème au classement général final, ces dernières années, en attestent.', 'Ferry', 'Sports d''Hiver'),
(DEFAULT, 'Biathlète autrichien, considéré comme un des plus rapides sur les skis, je remporte le classement général de la Mass-Start en 2009.', 'Landertinger', 'Sports d''Hiver'),
(DEFAULT, 'Je suis un biathlète norvégien, considéré comme le plus rapide à ski, je n''ai malheureusement pas la même réussite au tir, ce qui ne me permet pas de jouer les premiers rôles. je suis...', 'Berger', 'Sports d''Hiver'),
(DEFAULT, 'Sportif autrichien surnommé Felitsche, je participe au combiné nordique, et remporte de nombreuses victoires, dont la plus belle : la médaille d''or aux J.O de Turin en 2006.', 'Gottwald', 'Sports d''Hiver'),
(DEFAULT, 'Finlandais spécialiste du Combiné Nordique, et malgré quelques difficultés au saut, j''ai survolé les épreuves à ski, qui m''ont apporté mes quatre Globes de Cristal.', 'Manninen', 'Sports d''Hiver'),
(DEFAULT, 'Spécialiste du combiné nordique finlandais, je suis la relève d''Hannu Manninen, mais ce sont mes qualités de sauteur qui m''apportent le gros globe de Cristal en 2009.', 'Koivuranta', 'Sports d''Hiver'),
(DEFAULT, 'Sportif allemand, spécialiste du Combiné, j''ai livré, pendant des années, avec Hannu Manninen une des plus belles batailles offertes par les sports d''Hiver, et j''ai remporté, au passage, trois globes de Cristal.', 'Ackermann', 'Sports d''Hiver'),
(DEFAULT, 'Sportif français, participant au Combiné Nordique, je suis, avec Lamy-Chappuis, considéré comme le français le plus rapide à ski.', 'Lacroix', 'Sports d''Hiver'),
(DEFAULT, 'Je suis un américain, participant au Combiné Nordique, j''ai livré de belles batailles avec Lamy-Chappuis, me permettant d''accrocher la troisième place au général en 2008. Je suis...', 'Demong', 'Sports d''Hiver'),
(DEFAULT, 'Champion américain de Combiné Nordique , j''ai remporté, à Liberec, deux médailles d''or aux championnats du Monde 2009, après être sorti de ma retraite. Je suis... ', 'Lodwick', 'Sports d''Hiver'),
(DEFAULT, 'Sportif norvégien, j''ai livré, à coup de meilleur temps à ski, une lutte fratricide avec Hannu Manninen. Mes limites au saut ne m''ont, pour l''instant, pas permis de remporter un globe de Cristal.', 'Moan', 'Sports d''Hiver'),
(DEFAULT, 'Jeune sportif français, qui après avoir remporté des titres en espoir, fais, actuellement, avec Lamy-Chappuis et Lacroix, partie intégrante du groupe France.', 'Braud', 'Sports d''Hiver'),
(DEFAULT, 'Athlète italien, spécialiste du Combiné Nordique, je monte, fin 2009 et à seulement 19 ans, sur mon premier podium en Coupe du Monde.', 'Pittin', 'Sports d''Hiver'),
(DEFAULT, 'Sportif norvégien prénommé Peter, j''ai terminé deuxième de la Coupe du Monde 2008, après de belles victoires acquises par des sauts décisifs.', 'Tande', 'Sports d''Hiver'),
(DEFAULT, 'Famille de cyclistes russes, c''est Ag2r qui nous rassemblent sous le même maillot pour la saison 2008/09.', 'Efimkin', 'Cyclisme'),
(DEFAULT, 'Fils de grand champion français, j''ai rejoins Ag2r La Mondiale après de nombreuses saisons au Crédit Agricole.', 'Sebastien Hinault', 'Cyclisme'),
(DEFAULT, 'Cycliste, équipier modèle, et champion de Norvège 2009, je dois abandonner lors du Tour de France, à la suite d''une fracture de la clavicule.', 'Arvesen', 'Cyclisme'),
(DEFAULT, 'Sprinteur australien, poisson pilote de Mark Cavendish, j''évolue en 2009 chez Team Columbia, après avoir roulé deux saisons pour le Crédit Agricole.', 'Renshaw', 'Cyclisme'),
(DEFAULT, 'Cycliste français, je suis, à ma grande surprise, sélectionné pour les Championnats du Monde sur route, à Mendrisio, après une saison 2009 prometteuse.', 'Riblon', 'Cyclisme'),
(DEFAULT, 'Champion de Biélorussie, sprinteur de la Française des Jeux, je termine lanterne rouge du Tour de France 2009.', 'Hutarovich', 'Cyclisme'),
(DEFAULT, 'Premier japonais à terminer le Tour de France, je suis, en 2009, un baroudeur, mais surtout un équipier modèle de la B-Box.', 'Arashiro', 'Cyclisme'),
(DEFAULT, 'Cycliste colombien, je suis le plus jeune coureur sur le Tour de France 2009. Équipier de Valverde à la Caisse d''Epargne, je termine 5ème du Tour de Romandie.', 'Uran', 'Cyclisme'),
(DEFAULT, 'Cycliste Italien, on m''a décerné le titre de Super combatif au Tour de France 2009, après d''innombrables échappées. Je suis... ', 'Pellizotti', 'Cyclisme'),
(DEFAULT, 'Ancien coureur du Crédit Agricole, je suis, en 2009, le directeur sportif de Garmin-Slipstream. Je suis...', 'Vaughters', 'Cyclisme'),
(DEFAULT, 'Coureur portugais, équipier modèle chez Astana, j''ai mené Contador à la victoire lors du Tour de France 2009. Je suis... ', 'Paulinho', 'Cyclisme'),
(DEFAULT, 'Coureur italien, ayant porté le maillot Jaune pendant 8 jours sur le Tour de France 2009, je n''ai malheureusement pas réussi à terminer la Vuelta par la suite.', 'Nocentini', 'Cyclisme'),
(DEFAULT, 'Cycliste et puncheur autrichien, champion national à plusieurs reprises, je suis contrôlé positif à l''EPO pour la seconde fois, et suis interdit à vie de toute compétition.', 'Pfannberger', 'Cyclisme'),
(DEFAULT, 'Les trois français vainqueurs lors du Tour de France 2009 sont : Fedrigo Voeckler et...', 'Brice Feillu', 'Cyclisme'),
(DEFAULT, 'Équipe russe, soutenu par Poutine, je possède, en 2009, des coureurs tels que Karpets ou Steegmans. ', 'Katusha', 'Cyclisme'),
(DEFAULT, 'Maillot vert du Tour de France 2009, j''ai eu pour coéquipier Mark Renshaw ou encore Julian Dean.', 'Hushovd', 'Cyclisme'),
(DEFAULT, 'Le Luxembourg possède trois coureurs de grand talent : Andy et Franck Schleck et...', 'Kirchen', 'Cyclisme'),
(DEFAULT, 'Cycliste irlandais de l''équipe Cervélo, je me classe 9ème du Tour d''Espagne après y avoir remporté une victoire.', 'Deignan', 'Cyclisme'),
(DEFAULT, 'Jeune coureur français de la Française des Jeux, je remporte, à la surprise générale, une étape du Tour d''Espagne, qui vient récompenser une première saison prometteuse.', 'Anthony Roux', 'Cyclisme'),
(DEFAULT, 'Cycliste espagnol méconnu, courant pour une équipe continentale, ma régularité et mes capacités en montagne me permettent de me classer dans les 5 premiers des trois dernières Vueltas. Je suis...', 'Mosquera', 'Cyclisme'),
(DEFAULT, 'Champion d''Estonie sur route et contre-la-montre, à seulement 22 ans, coureur de la Cofidis, je remporte le Tour de l''Ain et participe entres autres à la Vuelta.', 'Taaramae', 'Cyclisme'),
(DEFAULT, 'Champion de France sur route 2009 au nez et à la barbe des équipes Pro Tour, je contribue à la découverte de mon équipe : Bretagne Armor-Lux. Je suis.', 'Champion', 'Cyclisme'),
(DEFAULT, 'Octobre 2009 : Décès d''un des cyclistes belges les plus doués de sa génération, il remporta Liège-Bastogne-Liège, ou encore Gand-Wevelgem. J''étais... ', 'Vandenbroucke', 'Cyclisme'),
(DEFAULT, 'En 2009, révolution sur la Vuelta, le maillot de Oro est remplacé. Mais quelle est la couleur du nouveau maillot du classement général ?', 'Rouge', 'Cyclisme'),
(DEFAULT, 'Après une suspension en 2008, Alessandro Petacchi revient, en 2009, dans l''équipe des "repentis", où se trouve Di Luca ou encore Savoldelli. Mais quel est le nom de cette équipe ?', 'LPR Brakes', 'Cyclisme'),
(DEFAULT, 'Famille de cyclistes argentins, l''ainé appartenait à la Saxo Bank, avant que son frère, fin 2009, ne le rejoigne. Nous sommes les...', 'Haedo', 'Cyclisme'),
(DEFAULT, 'Cycliste, référence du Cyclo-cross français sur la scène internationale, je me suis imposé progressivement au sein de la Française des Jeux, au point de participer aux trois Grands Tours.', 'Mourey', 'Cyclisme'),
(DEFAULT, 'Jeune Lituanien, ancien coureur du Crédit Agricole, j''ai signé en 2009 chez Cervélo, et ai remporté la même saison, le contre-la-montre final du Giro.', 'Konovalovas', 'Cyclisme'),
(DEFAULT, 'Je suis considéré comme le lieutenant de Valverde. Puncheur de talent, je termine la Vuelta 2009 à la 7ème place.  Je suis...', 'Joaquin Rodriguez', 'Cyclisme'),
(DEFAULT, 'Expérimenté cycliste italien, j''ai des faux airs de M.Pantani, et, en 2009, je remporte le maillot de Meilleur Grimpeur sur le Giro. Je suis...', 'Garzelli', 'Cyclisme'),
(DEFAULT, 'Jeune cycliste français, je remporte la médaille d''or dans la catégorie Espoirs aux championnats du Monde à Mendrisio.', 'Sicard', 'Cyclisme'),
(DEFAULT, 'Grandissime championne néerlandaise, j''ai tout gagné depuis mes débuts, mais échoue, en 2009, pour le troisième fois consécutive, à la deuxième place des Championnats du Monde sur route.', 'Marianne Vos', 'Cyclisme'),
(DEFAULT, 'Cycliste belge, ancien coureur de la Française des Jeux, je remporte, en fin de saison 2009, Paris-Tours et le Tour de Lombardie.', 'Gilbert', 'Cyclisme'),
(DEFAULT, 'Cycliste allemand, licencié chez Cervélo, après avoir lancé le sprint de très loin, je me fait sauté sur la ligne par Cavendish sur le Milan-San Remo, puis accumule les places d''honneur durant la saison 2009.', 'Haussler', 'Cyclisme'),
(DEFAULT, 'Cycliste français qui, grâce à mes belles performances sur les classiques, termine Premier français au Classement Pro Tour 2009.', 'Sylvain Chavanel', 'Cyclisme'),
(DEFAULT, 'Cycliste français, licencié chez Agritubel, je signe pour la saison 2010 dans l''équipe de Lance Arsmtrong, RadioShack.', 'Lequatre', 'Cyclisme'),
(DEFAULT, 'Cycliste français, chef de file du sprint dans l''Hexagone, je remporte la Coupe de France 2009.', 'Casper', 'Cyclisme'),
(DEFAULT, 'Cycliste hongrois, rouleur et coéquipier hors pair, j''ai remporté de nombreux contre-la-montre, avec le Crédit Agricole, puis en 2009, avec Katusha.', 'Bodrogi', 'Cyclisme'),
(DEFAULT, 'Petit prodige norvégien, aussi bon rouleur que grimpeur, je remporte des succès sur le Giro, et Gand-Wevelgem en 2009, avec Team Columbia, avant de signer en 2010 chez Sky.', 'Boasson Hagen', 'Cyclisme'),
(DEFAULT, 'Sprinteur allemand, appartenant à Team Columbia, je survole la Vuelta 2009 avec 4 victoires d''étapes et domine le Classement par Points.', 'Greipel', 'Cyclisme'),
(DEFAULT, 'Baroudeur néerlandais prénommé Martijn, spécialiste des classiques flandriennes, après avoir terminé 4ème de Paris-Roubaix l''année précédente, je confirme, en 2009, avec une quatrième place au Tour des Flandres.', 'Maaskant', 'Cyclisme'),
(DEFAULT, 'Quel sauteur à ski est surnommé "l''überflieger" ?', 'Martin Schmitt', 'Sports d''Hiver'),
(DEFAULT, 'Expérimenté sauteur à ski polonais, star et mythe de la discipline, j''ai survolé la discipline pendant plusieurs années, et détient le nombre de victoires en compétition, et je monte encore aujourd''hui sur les podiums à 32 ans.', 'Malysz', 'Sports d''Hiver'),
(DEFAULT, 'Sauteur à ski finlandais, de retour à la compétition, en 2009, après une année sabbatique, j''ai remporté cinq fois la tournée des Quatre Tremplins, ce qui fait de moi un des plus grands sauteurs de l''Histoire.', 'Ahonen', 'Sports d''Hiver'),
(DEFAULT, 'Sauteur à ski finlandais, on me surnomme "l''Homme qui ne sourit jamais", je suis...', 'Ahonen', 'Sports d''Hiver'),
(DEFAULT, 'Sauteur à ski suisse, aux faux airs d''Harry Potter, je reviens en forme en 2009 avec plusieurs succès, mais mon principal fait d''arme reste ma médaille d''or inattendue au J.O d''Hiver en 2002. Je suis...', 'Ammann', 'Sports d''Hiver'),
(DEFAULT, 'Je suis la ville possédant le plus grand Tremplin du Monde, tous les plus beaux records y sont tombés. Je suis le K185 de...', 'Planica', 'Sports d''Hiver'),
(DEFAULT, 'Sauteur à ski autrichien, surnommé "l''étoile du matin", je remporte de nombreuses victoires en fin de saison 2008/09, et suis dans la lignée des grands champions tels que Loitzl, ou autres Widholzl. Je suis...', 'Morgenstern', 'Sports d''Hiver'),
(DEFAULT, 'Prodige du saut à ski autrichien, je remporte mes premières compétitions internationales à seulement 16 ans, et, en 2009, je remporte le Classement général de la Coupe du Monde.', 'Schlirenzauer', 'Sports d''Hiver'),
(DEFAULT, 'Le saut à ski est basé sur le saut proprement dit, mai aussi sur la réception, pour optimiser la qualité de la réception, il faut poser le...', 'Telemark', 'Sports d''Hiver'),
(DEFAULT, 'Sauteur à ski norvégien, prénommé Bjorn, je possède, avec mes 239,5m, le record officiel du plus long saut jamais réalisé. Je suis...', 'Romoeren', 'Sports d''Hiver'),
(DEFAULT, 'Sauteur à ski français, en constante progression, je me classe régulièrement dans le Top 15, réussissant même un podium (3ème) en fin d''année 2009.', 'Chedal', 'Sports d''Hiver'),
(DEFAULT, 'Sauteur à ski français qui, malgré des difficultés en 2009, a longtemps été recordman de France avant d''être dépossédé de ce titre par E.Chedal. Je suis David...', 'Lazzaroni', 'Sports d''Hiver'),
(DEFAULT, 'Petite perle de la Mannschaft, et digne successeur de M.Schmitt, je monte, en fin d''année 2009 et à seulement 18 ans, sur un podium en Coupe du Monde. Je suis...', 'Bodmer', 'Sports d''Hiver'),
(DEFAULT, 'Compatriote de Simon Ammann, je remporte une médaille d''or inespérée aux Championnats du Monde Grand Tremplin de Liberec en 2009. Je suis...', 'Kuettel', 'Sports d''Hiver'),
(DEFAULT, 'Famille de sauteurs à ski finlandais, Matti, la cadet remporta de nombreux succès, tandis que l''ainé Jussi eu une carrière plus modeste. Nous sommes les...', 'Hautamaki', 'Sports d''Hiver'),
(DEFAULT, 'Sauteur à ski finlandais, digne successeur de J.Ahonen, je compte trois victoires en 2009 dont une mythique sur le tremplin de Planica. Mes bons résultats me permettent de terminer quatrième au classement général de la Coupe du Monde.', 'Olli', 'Sports d''Hiver'),
(DEFAULT, 'Pour tenter de se rapprocher du meilleur niveau mondial, l''Équipe de France de Saut à ski s''attache les services d''un entraineur de renom. Mais quelle est la nationalité de cet entraineur ? ', 'finlandais', 'Sports d''Hiver'),
(DEFAULT, 'En déficit de sauteurs à ski performants pour le concours par équipes 2009, l''Equipe de France s''octroie les services d''un talentueux athlète. Qui est-il ?', 'Lamy-Chappuis', 'Sports d''Hiver'),
(DEFAULT, 'En 2009, l''entraineur adjoint de l''Équipe de France de Saut à ski n''est autre que le dernier vainqueur français en Coupe du Monde. Qui est-il ?', 'Dessum', 'Sports d''Hiver'),
(DEFAULT, 'Sauteur à ski russe, ma régularité me permet de monter sur quelques podiums et de terminer 5ème de la Coupe du Monde 2009, sans jamais remporter le moindre concours au cours de ma carrière. Je suis...', 'Vassiliev', 'Sports d''Hiver'),
(DEFAULT, 'Sauteur à ski japonais, qui en 2009, et à 38 ans, devient le vainqueur d''un concours le plus âgé de l''Histoire. ', 'Okabe', 'Sports d''Hiver'),
(DEFAULT, 'Ensemble de sauteurs à ski classés dans les dix premiers mondiaux, ces derniers privilégient d''une immunité lors des qualifications. Ces sauteurs font partis du groupe des...', 'protégés', 'Sports d''Hiver'),
(DEFAULT, 'Star australienne longtemps pressentie à Bayonne, je signe finalement, fin 2009, pour le Leicester, et vient renforcer leur ligne de trois-quart.', 'Tuqiri', 'Rugby'),
(DEFAULT, 'Ancien troisième ligne et capitaine emblématique de Montauban, je succède, en 2009, à L.Travers et L.Labit au poste d''entraineur de Montauban.', 'Marc Raynaud', 'Rugby'),
(DEFAULT, 'Pilier camerounais, toujours un casque sur la tête, je participe à la finale du Challenge Européen en 2009, et fête une sélection avec les Barbarians la même année. Je suis...', 'Tchougong', 'Rugby'),
(DEFAULT, 'Demi de Mêlée formé au RC Metz, je fais mes gammes à Bourgoin Jailleu, avant de taper dans l''œil de Vern Cotter, par ma vivacité et ma qualité de passe. Je suis...', 'Parra', 'Rugby'),
(DEFAULT, 'Véritable malédiction perpignanaise, en 2009, joker médical, joueur replacé, titulaire, ou simple remplaçant tous se blessent à un poste clé. Mais lequel ?!', 'demi d''ouverture', 'Rugby'),
(DEFAULT, 'Troisième ligne sud-africain, évoluant à Brive, mes remarquables performances en 2009 tapent dans l''oeil de M.Lièvremont qui me voit un avenir en bleu, blanc, rouge. Je suis...', 'Claassen', 'Rugby'),
(DEFAULT, 'Centre anglais d''origine néo-zélandaise, je signe, en 2009, à Brive après une saison remarquable avec les Wasps et le XV de la Rose.', 'Flutey', 'Rugby'),
(DEFAULT, 'Arrière talentueux mais fragile, après mon départ du Stade Français, je suis longtemps resté sans club, avant de trouver refuge à Brive, fin 2009.', 'Jeanjean', 'Rugby'),
(DEFAULT, 'Rugbyman roumain, après plusieurs saisons à Pau, je viens renforcer la ligne arrière d''Albi,fin 2009, qui utilise avant tout ma qualité de jeu au pied, par des drops ou des pénalités.', 'Dumitras', 'Rugby'),
(DEFAULT, 'Pilier français formé à Albi, qui après une saison décevante avec le Stade Français, a rejoins son club formateur, en 2009.', 'Correia', 'Rugby'),
(DEFAULT, 'Demi de mêlée samoan, qui après l''arrivée de Parra à Clermont en 2009 à fait le chemin inverse pour rejoindre Bourgoin et regagner du temps de jeu. Je suis...', 'John Senio', 'Rugby'),
(DEFAULT, 'Meilleur contreur du Top 14, troisième ligne aile français, j''ai quitté Montauban pour rejoindre les rangs du Castres Olympique en 2009. Je suis...', 'Caballero', 'Rugby'),
(DEFAULT, 'Jeune troisième ligne français, formé au Stade Toulousain et qui, après une belle saison avec le Stade Montois en Top 14, a rejoint les rangs de Montpellier en 2009.', 'Giraud', 'Rugby'),
(DEFAULT, 'Famille de rugbymen français, tous deux demi de mêlée, nous sommes, en 2009, l''avenir du Montpellier Herault. Nous sommes les...', 'Tomas', 'Rugby'),
(DEFAULT, 'Rugbyman polyvalent capable de couvrir tous les postes dans les lignes arrières, j''ai joué au Stade français plusieurs saisons avant de signer il y a quelques années à Montpellier. Je suis, en 2009, et à 34 ans, un arrière expérimenté.', 'Sarramea', 'Rugby'),
(DEFAULT, 'Rugbyman écossais international évoluant au poste d''arrière, je signe, en 2009, à Toulon, après avoir évolué à Sale et Glasgow.', 'Rory Lamont', 'Rugby'),
(DEFAULT, 'Jeune international espoir, champion du monde 2006 avec L.Beauxis, après quelques matchs prometteurs à la mêlée en 2009, je signe sur la Rade, pour rejoindre la bande à Saint André. Je suis...', 'Cibray', 'Rugby'),
(DEFAULT, 'Trois-quart centre italien, je suis repositionné à l''arrière par N.Mallet en sélection, je tarde à m''imposer après mon transfert de Biarritz au Racing Métro, en 2009.', 'Masi', 'Rugby'),
(DEFAULT, 'En 2009, le Racing Métro réussit un gros coup sur le marché des transferts en enrôlant la star sud-africaine : François Steyn. Mais à quel club du Super 14 appartenait-il avant la transaction ?', 'Natal Sharks', 'Rugby'),
(DEFAULT, 'Jeune pilier formé au Stade français, je m''exile au Stade Toulousain en 2007, mais mes performances et la concurrence au poste ne me permettent pas d''être, en 2009, un élément incontournable du XV composé par G.Novès.', 'Montes', 'Rugby'),
(DEFAULT, 'Brock James termine l''exercice 2008/09 comme meilleur réalisateur du Top 14. Mais quel joueur anglais, plus connu pour son jeu au pied que pour ses relances, prend la deuxième place ? ', 'Goode', 'Rugby'),
(DEFAULT, 'Coureur néo-zélandais, ancien poisson pilote d''Hushovd, il fût celui de Farrar pendant les Grands Tours 2009. Je suis...', 'Dean', 'Cyclisme'),
(DEFAULT, 'Quel arrière, buteur régulier, du Castres Olympique est surnommé Robocop ?', 'Teulet', 'Rugby'),
(DEFAULT, 'Seul gallois présent dans l''équipe type de la saison 2009 (source : L''Équipe) , on me présente comme le digne successeur de l''ailier S.Williams. Je suis...', 'Halfpenny', 'Rugby'),
(DEFAULT, 'L''USAP remporte, en 2009, le titre de Champion de France du Top 14 et est maintenant la 5ème équipe française la plus titrée. Mais avec combien de Bouclier de Brennus ?', '7', 'Rugby'),
(DEFAULT, 'Désillusion majeure du rugby français en 2009, L''équipe de France échoue dans sa quête de Grand Chelem lors du Tournoi des VI Nations. Pire, elle s''incline à deux reprises. Mais à quelle place termine-t-elle ?', '3', 'Rugby'),
(DEFAULT, 'Troisième ligne castrais présent dans l''équipe type du Top 14 2009 (source : L''Équipe), j''ai renoncé, depuis mon arrivée en France, au maillot all-black. Je suis... ', 'Masoe', 'Rugby'),
(DEFAULT, 'Seul français présent dans l''équipe type de la saison 2009 (source : L''Équipe) , je m''inscris dans la lignée des P.De Villiers ou autres C.Califano. Je suis...', 'Barcella', 'Rugby'),
(DEFAULT, 'Aux Mondiaux de Val d''Isère 2009, une française crée la sensation en prenant la deuxième place du Super-G derrière L.Vonn. Qui est-elle ?', 'Marchand-Arvier', 'Sports d''Hiver'),
(DEFAULT, 'Aux Mondiaux de Val d''Isère 2009, Julien Lizeroux remporte deux médailles en slalom et super combiné. Mais de quel métal ?', 'argent', 'Sports d''Hiver'),
(DEFAULT, 'Grandissime championne de ski-cross, prénommée Ophélie, je remporte, en 2009, ma sixième Coupe du Monde de la discipline. Je suis...', 'David', 'Sports d''Hiver'),
(DEFAULT, 'Jeune et talentueux fondeur suisse, je remporte, en 2009, le classement général de la Coupe du Monde de Ski de fond. Je suis...', 'Cologna', 'Sports d''Hiver'),
(DEFAULT, 'Fondeuse polonaise, prénommé Justina, je remporte le classement général de la Coupe du Monde 2009, devant la slovène Petra Majdic. Je suis...', 'Kowalczyk', 'Sports d''Hiver'),
(DEFAULT, 'Skieur de fond français, spécialiste du sprint, qui, après une médaille d''argent surprise à Turin en 2006, tarde à m''imposer comme un cador de la discipline. Je suis...', 'Darragon', 'Sports d''Hiver'),
(DEFAULT, 'Skieur de fond français, prénommé Maurice, je monte, fin 2009, sur mon premier podium en Coupe du Monde, lors d''un 15km, à Davos.', 'Manificat', 'Sports d''Hiver'),
(DEFAULT, 'Fin 2009, à Davos, l''Équipe de France de Ski de fond réalise un véritable exploit en plaçant tous ses skieurs dans la Top 10. Mais combien étaient-ils ?', '5', 'Sports d''Hiver'),
(DEFAULT, 'Skieur de fond italien, connu pour mon mon bonnet jaune à pompon, je termine 4ème du classement général de la Coupe du Monde 2009, à plus de 35 ans. Je suis...', 'Piller Cottrer', 'Sports d''Hiver'),
(DEFAULT, 'Fondeuse finlandaise, je remporte le Tour de Ski 2009, après avoir été suspendu deux ans pour dopage. Je suis...', 'Kuitunen', 'Sports d''Hiver'),
(DEFAULT, 'Quel club, fut champion d''hiver de ligue 1 française en cette fin d''année 2009 ?', 'Bordeaux', 'Football'),
(DEFAULT, 'Dans quel club anglais, Frédéric PIQUIONNE, s''est il relancé ?', 'portsmouth', 'Football'),
(DEFAULT, 'Quel grand attaquant munichois a reçu un bon de sortie pour le mercato hivernal en cette fin d''année 2009 ?', 'toni', 'Football'),
(DEFAULT, 'Chef de file du ski de fond français, je vis une année 2009 difficile, malgré quelques podiums et une bonne fin de saison. Je suis...', 'Vittoz', 'Sports d''Hiver'),
(DEFAULT, 'Entraîneur, j''entraîne successivement : Corée du Sud, Australie et Russie, qui suis je ?', 'hiddink', 'Football'),
(DEFAULT, 'Skieur de fond, je termine meilleur français du Tour de Ski 2009, à la 6ème place du général. Je suis...', 'Gaillard', 'Sports d''Hiver'),
(DEFAULT, 'Quelle nation, élimine la Russie en barrages de la Coupe du Monde 2010 ? ', 'Slovénie', 'Football'),
(DEFAULT, 'Parmi ces équipes : Italie, Brésil, Angleterre et France, laquelle se retrouve dans le groupe de la Côte d''Ivoire lors de la Coupe du Monde 2010 ? ', 'Brésil', 'Football'),
(DEFAULT, 'Dans quel club, évolue depuis le mercato d''été 2009, le français Younes KABOUL ?', 'portsmouth', 'Football'),
(DEFAULT, 'Quel entraîneur, remplace Mark HUGUES, à la tête de Manchester City ?', 'mancini', 'Football'),
(DEFAULT, 'Quel joueur, qualifie l''Algérie pour la Coupe du monde 2010 ?', 'Yahia', 'Football'),
(DEFAULT, 'Dans quel pays, a eu lieu le match décisif entre l''Algérie et l''Egypte en barrages de la Coupe du Monde 2010 ?', 'soudan', 'Football'),
(DEFAULT, 'Combien de Portugais compte l''effectif du Real Madrid depuis l''été 2009 ?', '2', 'Football'),
(DEFAULT, 'Combien d''arbitres officiels compte un match d''Europa League ?', '5', 'Football'),
(DEFAULT, 'Je suis argentin et porte le numéro 22 de l''Internazionale, qui suis-je ?', 'milito', 'Football'),
(DEFAULT, 'Je suis licencié du poste d''entraîneur au Mans en cette fin d''année 2009 et dirige d''une main de maître l''équipe nationale du Burkina Faso, qui suis-je ?', 'duarte', 'Football'),
(DEFAULT, 'Ancien madrilène et bordelais, j''étudie, en cette fin d''année 2009, la possibilité de jouer pour l''Algérie, qui suis-je ? ', 'faubert', 'Football'),
(DEFAULT, 'Combien d''équipes italiennes, participeront à la phase finale de Ligue des Champions 2009/2010 ? ', '3', 'Football'),
(DEFAULT, 'En 2009, dans quel club, a été prêté Andriy Shevchenko ?', 'dynamo kiev', 'Football'),
(DEFAULT, 'Quel est l''entraîneur de West Ham depuis l''été 2009 ?', 'zola', 'Football'),
(DEFAULT, 'Quel joueur autrichien est venu s''ajouter à l''effectif Interiste durant le mercato d''été 2009 ? ', 'arnautovic', 'Football'),
(DEFAULT, 'Quel est le plus jeune joueur de l''Histoire de Premier League à avoir débuté, en 2009, sa carrière avec le maillot des Blues ?', 'kakuta', 'Football'),
(DEFAULT, 'Skieur français, prénommé Cyprien, je monte pour la première fois sur un podium en Coupe du Monde, avec une troisième place, fin 2009, à Alta Badia.', 'Richard', 'Sports d''Hiver'),
(DEFAULT, 'Jeune patineur français, je remporte, en 2009, et à 19 ans, les championnats de France devant Y.Ponsero et A.Préaubert. Je suis...', 'Amodio', 'Sports d''Hiver'),
(DEFAULT, 'Champion allemand de bobsleigh, je participe, en fin 2009, et à 36 ans, à ma dernière saison Coupe du Monde, après avoir tout gagné. Je suis...', 'Lange', 'Sports d''Hiver'),
(DEFAULT, 'Skieur polyvalent norvégien, je remporte, en 2009, le grand globe de Cristal, ainsi que le petit globe du Super-G. Je suis...', 'Svindal', 'Sports d''Hiver'),
(DEFAULT, 'Jeune biathlète française, prénommé Marie-Laure. Je monte, en 2009, sur mon premier podium, avec une prometteuse troisième place lors d''une poursuite.', 'Brunet', 'Sports d''Hiver'),
(DEFAULT, 'International gallois, je réalise, en 2009 et à la surprise générale, mon coming-out, en avouant mon homsexualité. Je suis...', 'Gareth Thomas', 'Rugby'),
(DEFAULT, 'L''année 2009 a été marquée par la première séance de tirs au but en H-Cup. Mais quel vaillant troisième ligne gallois, prénommé Martyn, manqua le tir au but décisif ?', 'Williams', 'Rugby'),
(DEFAULT, 'Talentueux international français évoluant à Perpignan, je remporte, en 2009, l''Oscar Midi Olympique. Je suis...', 'Mermoz', 'Rugby'),
(DEFAULT, 'Entraineur français, ayant mené mon équipe au Brennus en 2009, je remporte la même année l''Oscar Midi Olympique du Meilleur Entraîneur. Je suis...', 'Brunel', 'Rugby'),
(DEFAULT, 'Équipe de rugby française, je connais une saison 2008/2009 difficile en évitant de peu la relégation, mais arrive, tout de même, en finale du Challenge européen, finale perdue face à Northampton. Je suis...', 'Bourgoin-Jallieu', 'Rugby'),
(DEFAULT, 'Cycliste sur piste surpuissant, je remporte la vitesse individuelle aux Championnats du Monde 2009. Je suis...', 'Bauge', 'Cyclisme'),
(DEFAULT, 'Cycliste belge, prénommé Dominique. Après avoir été champion du Monde espoirs du Contre-la-montre, je remporte la médaille de bronze lors de la poursuite aux Championnats du Monde sur piste, en 2009.', 'Cornu', 'Cyclisme'),
(DEFAULT, 'Véritable surprise française aux Championnats du Monde sur piste en 2009, je remporte la médaille d''or du scratch, à seulement 22 ans. Je suis Morgan...', 'Kneisky', 'Cyclisme'),
(DEFAULT, 'Pistarde française de talent, spécialiste de la vitesse et du keirin, je remporte la médaille d''argent dans cette épreve aux Championnats du Monde 2009. Je suis... ', 'Clara Sanchez', 'Cyclisme'),
(DEFAULT, 'Nouvelle équipe sur le circuit Continental, j''impressionne, en 2009, avec mon recrutement labellisé ProTour : Evans, Hincapie, et autres Ballan... Je suis...', 'BMC Racing', 'Cyclisme'),
(DEFAULT, 'Après un passage éclair à Saint Etienne, je signe en faveur du Zénith Saint Pétersbourg, avant de me relancer avec Monaco en cette fin d''année 2009, qui suis-je ?', 'puygrenier', 'Football'),
(DEFAULT, 'Irlandais, je quitte Tottenham pour Liverpool, avant d''y revenir au mercato d''été 2009, qui suis-je ?', 'keane', 'Football'),
(DEFAULT, 'Ancien marseillais, je suis forcé de quitter Bastia après avoir reçu des menaces de mort du fait des mauvais résultas du club en ligue 2, qui suis-je ? ', 'arrache', 'Football'),
(DEFAULT, 'Attaquant italien, j''effectue mon retour a San Siro après avoir excellé pendant une saison du coté du Genoa, qui suis-je ? ', 'boriello', 'Football'),
(DEFAULT, 'Gardien international allemand, décédé le 11 Novembre 2009 dans un accident de train, je suis ...', 'enke', 'Football'),
(DEFAULT, 'Ballon d''or africain 2009, je suis ..', 'eto''o', 'Football'),
(DEFAULT, 'Quel équipe surprise, a disputé la finale de la Coupe des Confédérations 2009 face au Brésil ?', 'états unis', 'Football'),
(DEFAULT, 'Ailier gauche brésilien du championnat français , j''effectue ma première sélection dans un match amical face à l''Angleterre, à Doha, je suis ...', 'bastos', 'Football'),
(DEFAULT, 'En mal de temps de jeu au LOSC, je me relance du côté de strasbourg en 2009, en ligue 2, qui suis-je ?', 'fauvergue', 'Football'),
(DEFAULT, 'Prêté à Grenoble pour sa première saison en Ligue 1 par Lyon, il rejoint finalement ce club définitivement au mercato d''été, qui suis-je ?', 'paillot', 'Football'),
(DEFAULT, 'Capitaine emblématique, je rate la première partie de saison avec Boulogne-sur-Mer, qui suis-je ?', 'thill', 'Football'),
(DEFAULT, 'Ancien gardien Bordelais, je suis transféré à Toulouse en Décembre 2009, pour pallier aux blessures, qui suis-je?', 'valverde', 'Football'),
(DEFAULT, 'Dans quel club italien, Simone INZAGHI, a retrouvé du temps de jeu en cette fin d''année 2009 ?', 'lazio', 'Football'),
(DEFAULT, 'Quelle est la dernière équipe africaine qualifiée pour la Coupe du Monde 2010, en plus de celles ci : Côte d''Ivoire, Algérie, Cameroun, Nigeria et Afrique du Sud ?', 'ghana', 'Football'),
(DEFAULT, 'Après avoir quitté le SLUC en 2009, dans quel club s''est réfugié TJ Parker ?', 'villeurbanne', 'Basket-Ball'),
(DEFAULT, 'Sur quel score, le FC Barcelone bat en finale de Ligue des Champions 2009, le tenant du titre Manchester United ? ', '2-0', 'Football'),
(DEFAULT, 'Quel fut le meilleur buteur de la Coupe des Confédérations 2009 ?', 'luis fabiano', 'Football'),
(DEFAULT, 'Lors de la Coupe des confédérations 2009, le groupe A était composé de : Espagne, Afrique du Sud, Nouvelle-Zélande et ...', 'Irak', 'Football'),
(DEFAULT, 'Pour quel club, Kaba DIAWARA, a t-il signé cet été 2009 ?', 'arles-avignon', 'Football'),
(DEFAULT, 'Après une saison gâchée par des blessures, dans quel club, John MENSAH, s''est il relancé cet été 2009 ?', 'sunderland', 'Football'),
(DEFAULT, 'Prêté la saison dernière à la Fiorentina, il revient cet été 2009, et devient le troisième gardien officiel de l''AC Milan, qui est-il ? ', 'storari', 'Football'),
(DEFAULT, 'Qui est le président de la Fédération Française de Football en 2009 ?', 'escalettes', 'Football'),
(DEFAULT, 'En mal de temps de jeu au FC Metz, je suis prêté en fin de saison 2008/2009 à Sedan, qui suis-je ?', 'babacar gueye', 'Football'),
(DEFAULT, 'Ancien défenseur parisien, il se relance lors de la saison 2008/2009, à Hull City, qui est-il ? ', 'bernard mendy', 'Football'),
(DEFAULT, 'Comment se nomme le président français de la juventus de Turin ?', 'jean-claude blanc', 'Football'),
(DEFAULT, 'Capitaine de l''équipe de France Espoir, je figure comme un élément défensif indispensable pour le club de la capitale, qui suis-je ?', 'mamadou sakho', 'Football'),
(DEFAULT, 'Quel est le numéro de maillot de RONALDINHO à l''AC MILAN, durant la saison 2009/2010 ?', '80', 'Football'),
(DEFAULT, 'Espoir en devenir, je quitte le Rhône pour signer durant l''été 2009 du côté de l''OGC Nice, qui suis-je ?', 'mounier', 'Football'),
(DEFAULT, 'Milieu ghanéen évoluant en Italie, je suis exclu, fin Décembre 2009, du groupe de joueurs, destiné à jouer la Coupe d''Afrique 2010, qui suis-je ?', 'muntari', 'Football'),
(DEFAULT, 'Quel lieutenant de K.Bryant, considéré comme le meilleur 6ème Homme de la NBA, permet au Lakers de remporter le titre NBA, en 2009 ?', 'Odom', 'Basket-Ball'),
(DEFAULT, 'Quel joueur fut, en 2009, élu meilleur étranger de pro A ?', 'nichols', 'Basket-Ball'),
(DEFAULT, 'Dans quel club évolue, Austin Nichols lors de la saison 2009/2010 de pro A ?', 'orléans', 'Basket-Ball'),
(DEFAULT, 'Quel joueur, a été élu MVP français lors de la saison 2008/2009 de pro A ?', 'koffi', 'Basket-Ball'),
(DEFAULT, 'Quel joueur a été élu meilleur espoir de pro A, lors de la saison 2008/2009 ?', 'heurtel', 'Basket-Ball'),
(DEFAULT, 'Quel joueur a été élu meilleur défenseur de pro A, lors de la saison 2008/2009 ?', 'dobbins', 'Basket-Ball'),
(DEFAULT, 'Quel joueur évoluant en 2009, au Dallas Mavericks, a reçu le titre MIP lors de la saison 2008/2009 de pro A ? ', 'beaubois', 'Basket-Ball'),
(DEFAULT, 'Quel est le premier club NBA de Rodrigue Beaubois ?', 'dallas', 'Basket-Ball'),
(DEFAULT, 'Dans quel club, Ronny Turiaf, s''est réfugié après avoir quitté les lakers en 2009 ?', 'golden state', 'Basket-Ball'),
(DEFAULT, 'Dans quel club évoluait Boris Diaw, avant de rejoindre les Charlotte Bobcats en 2009 ?', 'phoenix suns', 'Basket-Ball'),
(DEFAULT, 'Derrière quelle grande star des SPURS, Ian Mahinmi tente-t-il de gagner du temps de jeu au poste de centre lors de la saison 2009 ?  ', 'duncan', 'Basket-Ball'),
(DEFAULT, 'Sauteur à ski autrichien, je remporte devant S.Ammann et G.Schlirenzauer, la tournée des 4 Tremplins, au début de l''année 2009. Je suis...', 'Loitzl', 'Sports d''Hiver'),
(DEFAULT, 'Famille de skieurs italiens, le frère est un concurrent direct de J.B. Grange en slalom, tout comme la soeur, spécialiste du slalom géant et du slalom. Nous sommes les...', 'Moelgg', 'Sports d''Hiver'),
(DEFAULT, 'Skieuse française, prénommé Taina, je suis une spécialiste du Géant, et monte sur mon premier podium, fin 2009, à 21 ans.', 'Barioz', 'Sports d''Hiver'),
(DEFAULT, 'Descendeur français, prénommé Johan, je reviens en forme et monte sur le podium à Val Gardena, après une terrible blessure aux deux genoux, au début de l''année 2009. Je suis...', 'Clarey', 'Sports d''Hiver'),
(DEFAULT, 'Descendeur canadien, prénommé John, je remporte à la surprise générale, la médaille d''or lors de la descente des Championnats du Monde à Val d''Isère, en 2009.', 'Kucera', 'Sports d''Hiver'),
(DEFAULT, 'Fin 2009, Julien Dupuy est suspendu pour 6 mois par l''ERC. Mais quel mauvais geste est responsable de cette sanction disciplinaire ?', 'Fourchette', 'Rugby'),
(DEFAULT, 'Équipe d''Afrique du Sud, je remporte le Super 14, en 2009, avant de voir ma star, B.Habana, rejoindre les Stormers. ', 'Bulls', 'Rugby'),
(DEFAULT, 'Province sud-africaine, qui après avoir recruté Michalak en 2008, se paye les services du magicien, Juan Martin Hernandez, en 2009.', 'Sharks', 'Rugby'),
(DEFAULT, 'Après l''éviction de Laurent Seigne, en 2009, je prends seul les commandes de l''entrainement brisviste. Ancien demi de mêlée international, je suis Christophe...', 'Laussucq', 'Rugby'),
(DEFAULT, 'Demi de mêlée international argentin, qui malgré les propositions de clubs du Top 14, en 2009, après la relégation de son club, décide de continuer l''aventure avec Dax, en Pro D2.', 'Vergallo', 'Rugby'),
(DEFAULT, 'Fantasque joueur fidjien, connu autant pour mon indiscipline que pour ma puissance. Je reviens, en 2009, au niveau qui a fait de moi, le meilleur joueur du Top 14, avec Agen.', 'Caucaunibuca', 'Rugby'),
(DEFAULT, 'Cycliste français de la FdJ, ancien puncheur du Crédit Agricole, qui, après une belle 10ème place à Paris-Nice, confirme en terminant 10ème du Tour de France 2009.', 'Le Mevel', 'Cyclisme'),
(DEFAULT, 'Champion de cyclisme sur route finlandais, je participe, en 2009, avec la FdJ au Tour de France, et y porte le maillot de Meilleur Grimpeur.', 'Veikkanen', 'Cyclisme'),
(DEFAULT, 'Expérimenté cycliste français, après une belle fin de saison 2009 avec Agritubel, je signe, pour un dernier challenge, à la Caisse d''Epargne. ', 'Moreau', 'Cyclisme'),
(DEFAULT, 'Cycliste irlandais, je suis champion national en 2009. Dans la lignée de mon père Stephen, je termine mon premier Tour de France à la 29ème place. ', 'Nicolas Roche', 'Cyclisme'),
(DEFAULT, 'Prometteur cycliste allemand, prénommé Tony, qui, après de nombreuses places d''honneur, en 2009, remporte la médaille de bronze aux Championnats du Monde de contre-la-montre à Mendrisio.  ', 'Martin', 'Cyclisme'),
(DEFAULT, 'Cycliste français, coéquipier modèle en montagne, et capitaine de route d''Ag2r la Mondiale, je mets un terme à ma carrière, en 2009, à 39 ans.', 'Goubert', 'Cyclisme'),
(DEFAULT, 'Cycliste belge, prénommé Niels, je remporte, en 2009, devant mon rival, Sven Nys, le titre de Champion du Monde de Cyclo-cross. ', 'Albert', 'Cyclisme'),
(DEFAULT, 'Grandissime champion de Cyclo-cross belge, je survole la discipline depuis plusieurs années et remporte, en 2009, et pour la 5ème fois consécutive le classement de la Coupe du Monde. Je suis...', 'Nys', 'Cyclisme'),
(DEFAULT, 'Ancien rennais, lyonnais mais aussi stéphanois, je prends les commandes de Dijon en tant qu''entraineur durant la saison 2009/2010, qui suis-je ?', 'carteron', 'Football'),
(DEFAULT, 'Grand espoir anglais, je suis transféré été 2009 du côté de Chelsea, je quitte alors mon club formateur Manchester City, qui suis-je ?', 'sturridge', 'Football'),
(DEFAULT, 'Milieu offensif tunisien, formé à Amiens, je suis l''un des principaux artisans du bon début de saison 2009 de Valenciennes, qui suis-je ?', 'Ben Khalfallah', 'Football'),
(DEFAULT, 'Ancien monégasque et caennais, je suis prêté par mon club, au Glasgow Rangers pour la saison 2009/2010, qui suis-je ?', 'rothen', 'Football'),
(DEFAULT, 'Championnats du Monde 2009 à Val d''Isère : la descente femmes est remporté par l''américaine...', 'Vonn', 'Sports d''Hiver'),
(DEFAULT, 'Championnats du Monde 2009 à Val d''Isère : belle performance d''ensemble des françaises en descente, avec, pour point d''orgue, la 4ème place de Marion...', 'Rolland', 'Sports d''Hiver'),
(DEFAULT, 'Skieuse allemande, sœur de Susanne, elle aussi skieuse, je remporte le slalom aux Championnats du Monde 2009 à Val d''Isère.   ', 'Maria Riesch', 'Sports d''Hiver'),
(DEFAULT, 'Prodige suisse, prénommée Lara, je termine 2ème de la descente femme des Championnats du Monde 2009 à Val d''Isère, à seulement 18 ans. Je suis... ', 'Gut', 'Sports d''Hiver'),
(DEFAULT, 'Ailier international français, je rejoins pour la saison 2008/2009, les Trail Blazers de Portland, qui suis-je ?', 'batum', 'Basket-Ball'),
(DEFAULT, 'Slalomeur autrichien, prénommé Manfred, ma médaille d''or aux Championnats du Monde à Val d''Isère vient récompenser une belle saison 2009.', 'Pranger', 'Sports d''Hiver'),
(DEFAULT, 'Pivot asiatique, j''entame ma 7 ème saison avec les Houston Rockets en 2009, qui suis-je ?', 'yao ming', 'Basket-Ball'),
(DEFAULT, 'Skieur croate, spécialiste du slalom, je termine la saison 2009, en échouant de peu dans la quête du petit Globe de Cristal dans ma discipline de prédilection.', 'Ivica Kostelic', 'Sports d''Hiver'),
(DEFAULT, 'Ancien manager et entraineur, j''occupe en 2009, la place de DTN à la Fédération Française de Football , qui suis-je ?', 'houiller', 'Football'),
(DEFAULT, 'Attaquant transféré au Mercato hivernal 2009, il quitte le FC Metz pour rejoindre Fribourg, en Allemagne, qui est-il ?', 'papiss cisse', 'Football'),
(DEFAULT, 'Fils d''un mythique gardien mancunien, je rejoins Notts County en juillet 2009 avec Sol Campbell entre autre, qui suis-je ?', 'kasper schmeichel', 'Football'),
(DEFAULT, 'Ancien défenseur gunner, je rejoins le club de Notts County en juillet 2009, qui suis-je ? ', 'sol campbell', 'Football'),
(DEFAULT, 'Attaquant français considéré comme un éternel espoir, je suis transféré au 
Mercato hivernal 2009 de l''Atletico Madrid au Sporting Lisbonne, qui suis-je ?', 'sinama-pongolle', 'Football'),
(DEFAULT, 'Face à quelle équipe, les grecs du Panathinaïkós Athènes ont il remporté la finale de l''Euroligue 2009 ?', 'Moscou', 'Basket-Ball'),
(DEFAULT, 'L''été 2009 est marqué par une affaire entre France et Nouvelle Zélande. Ces rixes sont dus aux mensonges d''un jeune et prometteur français, au gabarit impressionnant. Il se prénomme...', 'Bastareaud', 'Rugby'),
(DEFAULT, 'Troisième ligne des London Irish, je fête ma première sélection, avec mon frère Delon, sous le maillot du XV de la Rose, en 2009.', 'Steffon Armitage', 'Rugby'),
(DEFAULT, 'Quelle équipe, est en 2009, la plus titrée en Euroligue depuis sa création en 1958 ?', 'real madrid', 'Basket-Ball'),
(DEFAULT, 'Meneur serbe du Tau Vitoria, je suis le meilleur marqueur de l''Euroligue 2008/2009 ?', 'Rakocevic', 'Basket-Ball'),
(DEFAULT, 'Quelle équipe anglaise à la chance de compter, en 2009, dans ses rangs, les deux frères Armitage, Delon et Steffon ? ', 'London Irish', 'Rugby'),
(DEFAULT, 'Ancien ailier de Dax et du Stade français, je suis recruté par le Racing Métro, en 2009, pour mes qualités de vitesse et de finisseur. Je suis...', 'Saubade', 'Rugby'),
(DEFAULT, 'Quel ancien international français s''occupe, en 2009, des lignes arrières du XV de France ?', 'N''tamack', 'Rugby'),
(DEFAULT, 'Quelle équipe a remporté l''Euroligue 2009, à Berlin, en dominant les russes du CSKA Moscou ?', 'Panathinaikos', 'Basket-Ball'),
(DEFAULT, 'Ailier argentin, prénommé Lucas, qui après une saison en demi-teinte à Dax, choisi de rejoindre les rangs d''Albi en 2009.', 'Borges', 'Rugby'),
(DEFAULT, 'Meneur grec du Panathinaïkos, je suis élu meilleur défenseur de l''Euroligue, saison 2008/2009, qui suis-je ?', 'Diamantidis', 'Basket-Ball'),
(DEFAULT, 'Demi d''ouverture néo-zélandais, qui en rejoignant les Harlequins, lors de la saison 2008/2009, tire un trait sur sa carrière internationale. Je suis...', 'Evans', 'Rugby'),
(DEFAULT, 'Arrière serbe, je suis transféré au Real Madrid, après avoir été élu meilleur espoir lors de l''Euroligue 2008/2009, qui suis-je ?', 'velickovic', 'Basket-Ball'),
(DEFAULT, 'Équipier modèle, et coureur espagnol expérimenté de Cervélo, je suis, à 40 ans, le cycliste le plus âgé du Tour de France 2009.', 'Cuesta', 'Cyclisme'),
(DEFAULT, 'Ailier anglais des Harlequins, surnommé Moners, je participe, en 2009, à mon premier Tournoi des 6 Nations.', 'Monye', 'Rugby'),
(DEFAULT, 'Surnommé la " bomba " au FC Barcelone et ancien joueur de NBA, je suis élu MVP de la saison régulière en Euroligue, saison 2008/2009 ?', 'Juan Carlos Navarro ', 'Basket-Ball'),
(DEFAULT, 'Ailier fidjien aux appuis hors norme, je mets un terme à ma carrière internationale pour me consacrer à mon club, Montauban. Je suis...', 'Delasau', 'Rugby'),
(DEFAULT, 'Arrière espagnol, formé à Barcelone, je signe à Memphis Grizzlies, en NBA, avant de revenir à mes premiers amours lors de la saison 2008/2009, qui suis-je ? ', 'Juan Carlos Navarro ', 'Basket-Ball'),
(DEFAULT, 'Ancien espoir du rugby français prénommé Pierre, j''ai du mal à m''imposer en deuxième ligne au Stade Français, après mon arrivée du Clermont Auvergne en 2008/09.', 'Vigouroux', 'Rugby'),
(DEFAULT, 'Grimpeur italien, surnommé "le Cobra", je suis suspendu pour dopage, puis rejoins Ceramica Flaminia, en fin d''année 2009.', 'Ricco', 'Cyclisme'),
(DEFAULT, 'Entraineur de Villeurbanne depuis la saison 2008/2009 de pro A, je prends les rênes de l''équipe de France de Basket ball en 2009, qui suis-je ?', 'collet', 'Basket-Ball'),
(DEFAULT, 'Entraineur de Bourges Basket, j''entame ma 7 ème saison avec l''équipe de France féminine de Basket Ball en 2009, qui suis-je ?', 'pierre vincent', 'Basket-Ball'),
(DEFAULT, 'Alors qu''il devait signer avec la Quick Step pour 2009 après la dissolution de la Gerolsteiner, un contrôle antidopage positif sur le Tour de France met fin aux rêves de ce rouleur allemand. Mais qui est-ce ?', 'Stefan Schumacher', 'Cyclisme'),
(DEFAULT, 'Combien de grands chelems, comporte le circuit ATP, en 2009 ?', '4', 'Tennis'),
(DEFAULT, 'Cycliste britannique, équipier modèle, je signe en 2009, chez Cervélo. Mes qualités sur les pavés m''ont permis de me distinguer dans Paris-Roubaix et Gand-Wevelgem.', 'Hammond', 'Cyclisme'),
(DEFAULT, 'Cycliste australien, ancien du Crédit Agricole, je signe chez Cervélo, en 2009, et remporte, la même année, une étape sur le Giro et une sur la Vuelta.', 'Gerrans', 'Cyclisme'),
(DEFAULT, 'Sur le circuit ATP , deux Indiens figurent dans le Top Ten Mondial de Double en 2009, ils sont : Paes et ...', 'bhupathi', 'Tennis'),
(DEFAULT, 'Ancien coureur espagnol de Bouygues Télécom, avec qui j''ai remporté la Classica San Sebastian, je signe, en 2009, chez Cervélo pour mes qualités de puncheur. ', 'Florencio', 'Cyclisme'),
(DEFAULT, 'L''année 2009 est l''opportunité de voir le retour d''un banni, suspendu pour dopage. Surnommé "Chicken Legs", il s''agit bien sûr de...', 'Michael Rasmussen', 'Cyclisme'),
(DEFAULT, 'Gaucher canadien et coéquipier de Nenad Zimonjic en double, en 2009, je me considère comme un réel joueur de Double, qui suis-je ? ', 'nestor', 'Tennis'),
(DEFAULT, 'Seul espagnol qui apprécie la pluie et les pavés, ce coureur de classiques confirme sa renommée en prenant la 6ème place de Paris-Roubaix 2009.', 'Flecha', 'Cyclisme'),
(DEFAULT, 'Coéquipier de Nestor en double et droitier serbe, je figure au 3 ème rang Mondial en Double en 2009, qui suis-je ? ', 'zimonjic', 'Tennis'),
(DEFAULT, 'Sprinteur baroudeur français, souvent considéré comme le plus petit du peloton, cela ne m''empêche pas de remporter une étape sur le Tour de France en 2009.', 'Dumoulin', 'Cyclisme'),
(DEFAULT, 'Entrainé par Magnus Norman, j''occupe fin d''année 2009, une excellente 8 ème place mondiale, qui suis-je ?', 'soderling', 'Tennis'),
(DEFAULT, 'Cycliste français, je préfère les coups d''éclats aux performances régulières. Je confirme mes capacités de grimpeur avec le maillot de Meilleur Grimpeur sur la Vuelta 2009.', 'Moncoutié', 'Cyclisme'),
(DEFAULT, 'Puncheur " colérique " et détenteur de 14 titres sur le circuit ATP, j''obtiens mon meilleur classement en aout 2009, une 2ème place mondiale, qui suis-je ?', 'murray', 'Tennis'),
(DEFAULT, 'Surnommé le Mont Chauve, l''année 2009 a vu Garate triompher à mon sommet lors de l''avant dernière étape du Tour de France 2009. Je suis...', 'Mont Ventoux', 'Cyclisme'),
(DEFAULT, 'Ancien directeur de TF1, je prends la présidence de l''Olympique de Marseille, en 2009, qui suis-je ?', 'dassier', 'Football'),
(DEFAULT, 'Cycliste belge appartenant à Silence-Lotto, après la défaillance de mon leader lors du Tour de France 2009, je prends le leadership et termine à une prometteuse 15ème place.', 'Van den Broeck', 'Cyclisme'),
(DEFAULT, 'Équipe américaine de rouleurs, je présente sur le Tour de France 2009, le champion du Monde contre-la-montre, et les champions d''Australie, d''Allemagne, et du Luxembourg du contre-la-montre.', 'High Road', 'Cyclisme'),
(DEFAULT, 'Le Tour de France 2009 est marqué par la victoire de Contador. Mais lors du podium final, quel pays est mis à l''honneur à la place de l''hymne espagnol ?', 'Danemark', 'Cyclisme'),
(DEFAULT, 'Pour la première fois sur le Tour de France, Quick Step présente deux francais en la personne de S.Chavanel et du puncheur...', 'Jerome Pineau', 'Cyclisme'),
(DEFAULT, 'Prometteur grimpeur français, ancien coureur du Crédit agricole. Je confirme les espoirs placés en moi par Bernaudeau, mon directeur sportif, en terminant 4ème au classement du Meilleur Jeune au Tour de France 2009.', 'Pierre Rolland', 'Cyclisme'),
(DEFAULT, 'Champion de VTT, ou cycliste en devenir, je remporte le championnat de France 2009 du CLM, et représente le France aux Championnats du Monde à Mendrisio, où je prends une belle 12ème place.', 'Peraud', 'Cyclisme'),
(DEFAULT, 'Vainqueur du Super G des Championnats du Monde 2009, j''en deviens le plus vieux vainqueur. Suisse, de 35 ans, je remporte, la même année, le petit globe de Cristal du Géant.', 'Cuche', 'Sports d''Hiver'),
(DEFAULT, 'Polyvalent skieur suisse, je me révèle, en 2009 et du haut des mes 23 ans, avec une médaille d''or aux Championnats du Monde à Val d''Isère 2009 et le petit globe de cristal du combiné.', 'Janka', 'Sports d''Hiver'),
(DEFAULT, 'Cycliste espagnol de la Caisse d''Épargne je remporte le Tour de France 2006, et signe fin 2009 chez Astana, en équipier de Luxe.', 'Oscar Pereiro', 'Cyclisme'),
(DEFAULT, 'Le maillot du Stade Français 2009 met en valeur une célèbre reine en la personne de...', 'Blanche de Castille', 'Rugby'),
(DEFAULT, 'Skieur autrichien, prénommé Benjamin, ma régularité et ma polyvalence me permettent de terminer, en 2009, sur le podium du Classement général de la Coupe du Monde, pour la 6ème année consécutive.', 'Raich', 'Sports d''Hiver'),
(DEFAULT, 'Grosse désillusion 2009, Championnats du Monde à Val d''Isère, alors qu''il était le grand favori du slalom, il sort lors de la deuxième manche et laisse les honneurs à un autre français, J.Lizeroux.', 'Grange', 'Sports d''Hiver'),
(DEFAULT, 'Famille de rugbymen argentins, l''aîné termine sa carrière du côté de Clermont-Auvergne, tandis que le cadet, revient fin 2009, avec le Stade Français, après un grave blessure. Nous sommes...', 'Ledesma', 'Rugby'),
(DEFAULT, 'Révélation du Top 14 2009 au poste d''ouvreur, Jonathan Wisniewski s''impose comme un titulaire en club, et frappe aux portes de l''Équipe de France. Mais quelle  est cette équipe, en 2009, qui l''a révélé ?', 'Racing Métro', 'Rugby'),
(DEFAULT, 'Fantasque skieur américain, mon ski tout en risque m''a valu de nombreux succès. Je veux, fin 2009, montrer que ma 15ème place lors du précédent exercice n''était qu''une erreur de parcours.', 'Bode Miller', 'Sports d''Hiver'),
(DEFAULT, 'Prometteur arrière français, je prends mes responsabilités en finale du Top 14, en juin 2009. Mes réussites au pied permettent à mon équipe de l''emporter face au Clermont-Auvergne. Je suis...', 'Porical', 'Rugby'),
(DEFAULT, 'Demi d''ouverture français au coup de pied surpuissant, je termine meilleur réalisateur français du Top 14, lors de la saison 2008/09.', 'Beauxis', 'Rugby'),
(DEFAULT, 'Équipe française, au recrutement ronflant, je remporte, avec 13 points d''avance sur mon dauphin Agen, la Pro D2, en 2009.', 'Racing Métro', 'Rugby'),
(DEFAULT, 'Attaquant Islandais, arrivé été 2009 à l'' AS Monaco, je désire quitter la principauté dès le mercato hivernal 2009/2010, qui suis-je ?', 'Gudjohnsen', 'Football'),
(DEFAULT, 'Rugbyman français capable de jouer deuxième ou troisième ligne. Je suis loin d''être un titulaire indiscutable au Stade Toulousain, mais je participe, en 2009, grâce à ma polyvalence, à 26 matchs avec l''équipe de G.Novès.', 'Lamboley', 'Rugby'),
(DEFAULT, 'Quelle équipe nationale, titrée à 7 reprises en championnats du Monde en 2009, domine le Basket féminin depuis ses débuts ?   ', 'états unis', 'Basket-Ball'),
(DEFAULT, 'Quelle équipe nationale féminine de Basket Ball, est actuelle Championne du Monde, un titre conquis au Brésil, en 2006 face, à la Russie ?', 'Australie', 'Basket-Ball'),
(DEFAULT, 'Quelle est la périodicité, en années, des championnats du Monde de Basket Ball féminin ?', '4', 'Basket-Ball'),
(DEFAULT, 'Formé à Southampton, avant de rejoindre les Blues et  Stamford Bridge, je me présente, depuis l''été 2009, comme le titulaire indiscutable au poste de défenseur gauche, à Manchester City, qui suis-je ?', 'bridge', 'Football'),
(DEFAULT, 'Petit feu follet et international anglais, je surprends mes adversaires, par ma vitesse et mes enchainements balle au pied; passé par Chelsea, je figure, indiscutablement, dans le Onze de départ de Manchester City en 2009, qui suis-je ?', 'wright-phillips', 'Football'),
(DEFAULT, 'Attaquant Sud Américain, passé du côté de l''Alliance Arena, je suis transféré été 2009 en provenance de Blackburn, à Manchester City, et compte, fin 2009, aucune titularisation en Premier League, qui suis-je ?', 'santa cruz', 'Football'),
(DEFAULT, 'Née le 25 mars 1971 au Texas, et évoluant à Houston, je suis en 2009, la joueuse américaine, la plus titrée dans l''histoire des championnats du Monde, qui suis-je ? ', 'swoopes', 'Basket-Ball'),
(DEFAULT, 'Ballon d''or 1991, je prends les rênes, le 30 Décembre 2009, de Châteauroux alors 18ème de Ligue 2, qui suis-je ?', 'papin', 'Football'),
(DEFAULT, 'Ancienne Numéro 1 Mondiale, je prends ma retraite le 3 décembre 2009, qui suis-je ?', 'mauresmo', 'Tennis'),
(DEFAULT, 'Attaquant Hondurien, et bloqué au poste par Milito, Eto''o et Balotelli, je suis prêté à Genoa, fin 2009 pour une durée de 6 mois, qui suis-je ?', 'suazo', 'Football'),
(DEFAULT, 'Ancien défenseur mythique néerlandais, je fais depuis 2009, les beaux jours de Galatasaray, en tant qu''entraineur, qui suis-je ?', 'rijkaard', 'Football'),
(DEFAULT, 'Attaquant, je suis présenté comme le futur prodige Américain dans les médias, mais je déçois très vite par mes prestations en Europe, je suis de retour en Décembre 2009 à Benfica,après un prêt stoppé par Belenenses, qui suis-je ?', 'freddy adu', 'Football'),
(DEFAULT, 'Dans un livre autobiographique, sorti fin 2009, j''évoque mon quotidien sportif gâché par la prise de substances illicites, qui suis-je ? ', 'agassi', 'Tennis'),
(DEFAULT, 'Attaquant fantaisiste, je suis l''objet d''une vive polémique, en 2009, à la suite de son licenciement par Chelsea, pour cause de dopage, quelques années plus tôt, qui suis-je ?  ', 'mutu', 'Football'),
(DEFAULT, 'Arrière latéral gauche, formé à Sochaux, comptant une sélection en équipe de France A'', je suis transféré été 2009 du côté de l''Espagne et plus précisément à Valence, qui suis-je ?  ', 'jérémy mathieu', 'Football'),
(DEFAULT, 'Arrivé sous forme de prêt chez les Rossoneri, en Décembre 2009, je n''en finis de surprendre par mon look extravagant, qui prend parfois le dessus sur mes performances footballistiques, qui suis-je ? ', 'beckham', 'Football'),
(DEFAULT, 'Quelle équipe, les Bleus de Raymond Domenech, affronteront lors de leur premier match, à la Coupe du Monde 2010, qui se déroulera en Afrique du Sud ?', 'uruguay', 'Football'),
(DEFAULT, 'Attaquant Suisse, je suis transféré été 2009 à Zurich, et suis le plus jeune buteur de l''histoire d''un championnat d''Europe, qui suis-je ?', 'vonlanthen', 'Football'),
(DEFAULT, 'Arrivé en 2009, du côté de l''ASVEL, quel club de renom, en pro A, Vincent Collet a-t-il entrainé auparavant ?', 'le mans', 'Basket-Ball'),
(DEFAULT, 'Milieu de terrain, appartenant à la Lazio de Rome, présenté, il y a encore quelques années, comme le futur " zizou ", j''inaugure ma première sélection avec les fennecs, qui suis-je ? ', 'meghni', 'Football'),
(DEFAULT, 'Grand attaquant italien d''origine Australienne, je joue pour les plus grands clubs européens, et notamment pour l''Internazionale, entre 1999 et 2005, je prends ma retraite le 22 Octobre 2009, qui suis-je ?', 'vieri', 'Football'),
(DEFAULT, 'Quelle équipe, a établi un nouveau record, qui est de 18 défaites de suite, correspondant donc, au plus mauvais début de saison de l''histoire de la NBA ?  ', 'new jersey', 'Basket-Ball'),
(DEFAULT, 'Les Nets ont établi le plus mauvais début de saison de l''histoire de la NBA, mais avec combien de défaites de suite ? ', '18', 'Basket-Ball'),
(DEFAULT, 'Milieu de Terrain valenciennois, je décline, fin  décembre 2009, la sélection avec les Aigles de Carthages, et ne disputera donc pas la Coupe d''Afrique des Nations, qui suis-je ?', 'Ben Khalfallah', 'Football'),
(DEFAULT, 'Titulaire indiscutable, en 2009, à la pointe du Real Madrid, dans quel club, Gonzalo HIGUAIN a-t-il fait ses armes ?', 'River Plate', 'Football'),
(DEFAULT, 'Verdasco, 9 ème Mondial, a pu participé au Masters de Londres 2009, réunissant les 8 meilleurs joueurs mondiaux, suite à une blessure d''un joueur, mais qui est il ?', 'roddick', 'Tennis'),
(DEFAULT, 'Tenant du Titre à Monte Carlo, je remporte une nouvelle fois cette finale, en 2009, face à Djokovic, qui suis-je ?', 'nadal', 'Tennis'),
(DEFAULT, 'Attaquant international allemand, je finis 3 ème meilleur buteur du championnat allemand avec Stuttgart lors de la saison 2008/2009, avant de rejoindre Munich l''été qui suit, qui suis-je ?', 'mario gomez', 'Football'),
(DEFAULT, 'Milieu offensif algérien, formé à Sochaux, je quitte la France pour rejoindre Wolfsburg, en Allemagne, durant l''été 2009, qui suis-je ?', 'karim ziani', 'Football'),
(DEFAULT, 'Robuste défenseur français, formé au RC France, j''arrive à Bordeaux été 2009, en provenance de Lorient, et me présente comme un titulaire indiscutable dans le Onze type de départ, qui suis-je ?', 'ciani', 'Football'),
(DEFAULT, 'Champion du monde 2006, je signe à la Roma, au Mercato hivernal 2009, afin de me relancer et de faire partie du groupe Italien qui s''envolera en juin 2010, pour l''Afrique du Sud, qui suis-je ?', 'toni', 'Football'),
(DEFAULT, 'Présente pour la première fois à Roland Garros 2009, je gagne cette même année l''édition junior, et suis élue fin 2009, à 16 ans, meilleure junior de l''année 2009, qui suis-je ?', 'mladenovic', 'Tennis'),
(DEFAULT, 'Défenseur sénégalais, Champion de France 2008/2009, je quitte mes camarades été 2009 pour rejoindre la cité fosséenne , qui suis-je ?
', 'souleymane diawara', 'Football'),
(DEFAULT, 'Seul joueur du Top Ten en 2009, à ne pas posséder d''équipementier officiel, je suis...', 'davydenko', 'Tennis'),
(DEFAULT, 'Ancien parmesan, je suis élu, en Décembre 2009, et pour la deuxième année consécutive, meilleur joueur de la zone AMSUD, qui suis-je ?', 'juan sebastian veron', 'Football'),
(DEFAULT, 'Ancien défenseur Nancéien, je reviens, fin Décembre 2009, en prêt à Saint-Étienne, pour une durée de 6 mois, qui suis-je ?', 'Diakhate', 'Football'),
(DEFAULT, 'Ancien Bordelais, je suis prêté, à la surprise générale, en Janvier 2009, du côté de Santiago Bernabeu, qui suis-je ? ', 'faubert', 'Football'),
(DEFAULT, 'Joueur des Denver Nuggets, je suis Franchise Player de mon équipe et meilleur scoreur de la NBA, en 2009, qui suis-je ?', 'carmelo anthony', 'Basket-Ball'),
(DEFAULT, 'Quel Sophomore est considéré, en 2009, comme le Franchise Player d''Oklahoma City ?', 'Kevin Durant', 'Basket-Ball'),
(DEFAULT, 'Rafael NADAL et son entraineur en 2009, présentent des liens très particuliers, en effet, Toni NADAL est son ...', 'oncle', 'Tennis'),
(DEFAULT, 'Roger Federer établit un record en 2009, il devient le seul joueur, a remporté, combien de titres du Grand Chelem ?', '15', 'Tennis'),
(DEFAULT, '2009, année de ma consécration, je parviens à me hisser dans le Top Ten, et même à décrocher une place de 5 ème joueur mondial le 6 avril 2009 que j''occuperai    jusqu''à la fin de la saison, qui suis-je ?', 'del potro', 'Tennis'),
(DEFAULT, 'Grand attaquant international Tchèque, je signe à l''AS Cannes, au Mercato hivernal 2009/2010, qui suis-je ?', 'koller', 'Football'),
(DEFAULT, 'Ancien attaquant international francais, presenté à ses débuts, comme le futur Jean Pierre Papin, je mets un terme à ma carrière en 2005 après être passé par Paris, Marseille ou encore le Celta Vigo; je rejoins le 1 er Juillet 2009, la cellule de recrutement de l''OL, qui suis-je ? ', 'Florian Maurice', 'Football'),
(DEFAULT, 'Quel fut le joueur, en 2009, élu meilleur espoir masculin français ?', 'mina', 'Tennis'),
(DEFAULT, 'Je suis retrouvé mort au pied de ma porte, quelques jours après avoir joué Roland Garros, qui suis-je ? ', 'montcourt', 'Tennis'),
(DEFAULT, 'Sex Symbol du tennis et ancien numéro 1 mondial,  je tire ma révérence à Bercy, en 2009, qui suis je ?', 'safin', 'Tennis'),
(DEFAULT, 'Je succède, en 2009, à Tim Henman dans le cœur des britanniques, qui suis je ?', 'murray', 'Tennis'),
(DEFAULT, 'Bête noire de Raphael NADAL, je suis le premier à le vaincre à Roland Garros, qui suis je ? ', 'soderling', 'Tennis'),
(DEFAULT, 'Joueuse ayant choqué le monde tennistique, après avoir déclaré à une arbitre de chaise : " je vais te tuer (...) "', 'serena williams', 'Tennis'),
(DEFAULT, ' Quel ancien joueur mythique a été bousculé par la presse, après avoir déclaré : '''' Je me suis dopé (...) '''' ?', 'agassi', 'Tennis'),
(DEFAULT, 'Je suis nommé capitaine de l''équipe de France de Fed Cup en 2009, qui suis je ? ', 'escudé', 'Tennis'),
(DEFAULT, 'Je suis pour quelques microgrammes de cocaines, suspendu 2 mois de tout tournois officiels, qui suis je ? ', 'gasquet', 'Tennis'),
(DEFAULT, 'Habitué à gagner des titres,  mes "mauvais" résultats cette année, sont dus en partie au divorce de mes parents, qui suis je ? ', 'nadal', 'Tennis'),
(DEFAULT, 'Après avoir fait un retour fracassant sur le circuit féminin, je termine cette année 2009 plus traquillement, qui suis je ? ', 'CLIJSTERS', 'Tennis'),
(DEFAULT, 'Actuellement blessée cette année, je figure plus souvent au coté de S.Nasri que sur les courts, qui suis je ? ', 'golovin', 'Tennis'),
(DEFAULT, 'Faisant partie indéniablement du top 10 féminin, nous sommes numero 1 en double, qui sommes nous ?  ', 'williams', 'Tennis'),
(DEFAULT, 'Je suis un indien, roi du double, qui suis je ? ', 'paes', 'Tennis'),
(DEFAULT, 'Où se deroulait en 2009, le masters chez les femmes ? ', 'doha', 'Tennis'),
(DEFAULT, 'Combien d''espagnols, se sont qualifiés pour le Masters de Londres 2009 ? ', '2', 'Tennis'),
(DEFAULT, 'Je succède, en 2009, à D.Safina au rang du numéro 1, qui suis-je ? ', 'serena  williams', 'Tennis'),
(DEFAULT, 'Au 1er Novembre 2009,
  Complétez:        1. Federer
                    2. Nadal
                    3. Djokovic
                    4. Murray 
                    5. .....
', 'del potro', 'Tennis'),
(DEFAULT, 'Comment se nomme l''entraineur français de G.Simon, en 2009 ? ', 'champion', 'Tennis'),
(DEFAULT, 'Numéro 1 mondial en double masculin, frères américains de grand talent, qui sommes nous ? ', 'bryan', 'Tennis'),
(DEFAULT, 'Cycliste français, éternel espoir de la discipline, malgré mes préférences pour les classiques, je me classe 3ème du Paris-Nice 2009 derrière Sanchez et Schleck. Je suis...', 'Sylvain Chavanel', 'Cyclisme'),
(DEFAULT, 'Équipe anglaise où s''illustre des joueurs comme Murphy, A.Tuilagi, ou Moody, je remporte le Championnat d''Angleterre en 2009. Je suis...', 'Leicester', 'Rugby'),
(DEFAULT, 'Star du rugby australien qui, malgré la dernière place de mon équipe au Tri-Nations 2009, arrive à terminer meilleur marqueur d''essais de ce dernier, à l''ouverture ou au centre. Je suis... ', 'Giteau', 'Rugby');









INSERT INTO CustomAnswer(id, answer, good, sport) VALUES 
(DEFAULT, 'Incroyable retourné acrobatique ! Quelle dextérité, mais surtout quel but !', TRUE , 'Football'),
(DEFAULT, 'Quel arrêt spectaculaire ! Une dextérité hors du commun pour ce gardien d''exception !', TRUE , 'Football'),
(DEFAULT, 'Lob extraordinaire des 35 mètres. Il voit la gardien avancé et le talent fait le reste ! Quel but !', TRUE,  'Football'),
(DEFAULT, 'Cette équipe produit un jeu exceptionnel ! Une véritable passe à 10 !', TRUE , 'Football'),
(DEFAULT, 'Cette équipe maitrise totalement son sujet. C''est un véritable récital !', TRUE , 'Football'),
(DEFAULT, 'Un nouveau duel remporté, quel hargne chez ce joueur...', TRUE , 'Football'),
(DEFAULT, 'Une action, un but ! Voilà du beau boulot ! ', TRUE , 'Football'),
(DEFAULT, 'Il n''a pas manqué d''enfoncer le clou sur ce contre assassin, intelligence et vitesse ont fait le reste ! ', TRUE , 'Football'),
(DEFAULT, 'Quel tacle assassin, l''arbitre n''hésite pas une seule seconde, et sort le rouge ! ', FALSE , 'Football'),
(DEFAULT, 'Quelle simulation ! Carton jaune mérité ! ', FALSE , 'Football'),
(DEFAULT, 'Tirage de maillot dans la surface... Que dit l''arbitre ? "Pénalty !" C''est terrible... ', FALSE , 'Football'),
(DEFAULT, 'Coup de coude ! Il sort sur civière. Voilà une dure fin pour ce courageux joueur.', FALSE , 'Football'),
(DEFAULT, 'Oh le méchant geste... Et c''est le carton rouge ! Le match est terminé pour lui ! ', FALSE , 'Football'),
(DEFAULT, 'Quelle occasion ratée, il n''avait plus qu''à pousser le ballon au fond des filets !', FALSE , 'Football'),
(DEFAULT, 'Coup-franc qui s''envole dans les tribunes ! Quelle occasion ratée...', FALSE , 'Football'),
(DEFAULT, 'Occasion I.M.M.A.N.Q.U.A.B.L.E. ! Et pourtant il la manque !  ', FALSE , 'Football'),
(DEFAULT, 'Seul devant la cage vide, il trouve le moyen d''envoyer le ballon dans les tribunes... ', FALSE , 'Football'),
(DEFAULT, 'Quel raté ! C''était plus dur de la mettre au à côté...', FALSE , 'Football'),
(DEFAULT, 'Un service-volée bien exécuté... Et tout est plus facile ! ', TRUE , 'Tennis'),
(DEFAULT, 'Un nouvel ace ! le 27ème aujourd''hui. Quelle précision ! ', TRUE , 'Tennis'),
(DEFAULT, 'Volée courte croisée imparable... Quelle intelligence de jeu ! ', TRUE , 'Tennis'),
(DEFAULT, 'L''amortie parfaitement distillée, voilà le signe des grands joueurs ! ', TRUE , 'Tennis'),
(DEFAULT, 'Quel coup droit le long de la ligne ! L''adversaire jette sa raquette de dépit...', TRUE , 'Tennis'),
(DEFAULT, 'Jeu, set, et match ! Une promenade de santé pour ce joueur d''exception ! ', TRUE , 'Tennis'),
(DEFAULT, 'Il alterne jeu court, jeu long avec une réussite insolente... Quel maitrise ! ', TRUE , 'Tennis'),
(DEFAULT, 'Nouveau rebond offensif, il domine vraiment dans la raquette !', TRUE , 'Basket-Ball'),
(DEFAULT, 'Et il score au buzzer ! Amazing ! ', TRUE , 'Basket-Ball'),
(DEFAULT, 'Bras roulé à l''ancienne... Et ca rentre ! Réussite insolente ! ', TRUE , 'Basket-Ball'),
(DEFAULT, 'Un dunk venu d''ailleurs, il y a du Michael Jordan dans ce joueur ! ', TRUE , 'Basket-Ball'),
(DEFAULT, 'Il enquille les paniers commes les perles !', TRUE , 'Basket-Ball'),
(DEFAULT, 'Le C.A.K.E ! Quel contre !  ', TRUE , 'Basket-Ball'),
(DEFAULT, 'Quel air-ball ! Il s''est véritablement troué sur ce shoot !', FALSE , 'Basket-Ball'),
(DEFAULT, 'Faute technique ! Attention, pris par la patrouille !', FALSE , 'Basket-Ball'),
(DEFAULT, 'Une attaque comme on les aime... Ce coureur est vraiment plein de panache ! ', TRUE , 'Cyclisme'),
(DEFAULT, 'Il dépose les leaders au pied du dernier col. Il s''envole vers la victoire... ', TRUE , 'Cyclisme'),
(DEFAULT, 'Il aime les pavés, et ca se voit... Quel trublion ! ', TRUE , 'Cyclisme'),
(DEFAULT, 'Véritable funambule en descente, il prend tous les risques...et ca paye ! ', TRUE , 'Cyclisme'),
(DEFAULT, 'Une crevaison... Va-t-il réussir à revenir sur la tête ?!', FALSE , 'Cyclisme'),
(DEFAULT, 'Il est irrémédiablement lâché, on ne le reverra pas de si tôt ! ', FALSE , 'Cyclisme'),
(DEFAULT, 'La tête dans la guidon, sale journée pour ce leader en difficulté... ', FALSE , 'Cyclisme'),
(DEFAULT, 'Quelle fluidité entre les piquets ! Il file vers la victoire ! ', TRUE , 'Sports d''Hiver'),
(DEFAULT, 'Un sans faute au tir, et tout est plus facile... ', TRUE , 'Sports d''Hiver'),
(DEFAULT, 'Un saut digne de l''Überfligier, quel grand champion !', TRUE , 'Sports d''Hiver'),
(DEFAULT, 'Dieu qu''il est rapide sur les skis, une nouvelle victoire en perspective !', TRUE , 'Sports d''Hiver'),
(DEFAULT, 'Prise de risque maximale dans cette descente... et ca paye ! Enorme !', TRUE , 'Sports d''Hiver'),
(DEFAULT, 'Quelle sortie de piste, il enfourche le piquet ! Une manche à oublier... ! ', FALSE , 'Sports d''Hiver'),
(DEFAULT, 'Terrible chute ! A vouloir trop en faire, il a oublié l''essentiel : rester sur les skis ! ', FALSE , 'Sports d''Hiver'),
(DEFAULT, 'Terrible désillusion ! Deux pioches au tir debout, et toutes ses chances de victoire qui s''envolent... ', FALSE , 'Sports d''Hiver'),
(DEFAULT, 'Quelle poussée en mêlée ! Enorme travail des avants, et c''est tout le stade qui se lève ! ', TRUE , 'Rugby'),
(DEFAULT, 'Et un en-avant qui vient mettre un terme à une bien belle action. Cruelle désillusion...', FALSE , 'Rugby'),
(DEFAULT, 'Il soigne ses trajectoires, c''est la tactique à adopter pour gagner aujourd''hui... ', TRUE , 'Sports d''Hiver'),
(DEFAULT, 'Il avale cette portion technique avec une facilité déconcertante. Quelle démonstration ! ', TRUE, 'Sports d''Hiver'),
(DEFAULT, 'Il va le faire... La médaille d''or est au bout ! ', TRUE, 'Sports d''Hiver'),
(DEFAULT, 'Quelle terrible chute dans ce mur verglacé. Skier sur les écarres n''est visiblement pas la bonne solution.', FALSE, 'Sports d''Hiver'),  
(DEFAULT, 'Terrible chute, il finit sa course dans le décor !' , FALSE, 'Sports d''Hiver'),
(DEFAULT, 'Quelle raffale de vent, un saut raté mais pas par manque de talent...', FALSE,  'Sports d''Hiver'),
(DEFAULT, 'Quel jeu au pied pitoyable, il ne trouve même pas la pénaltouche ! ', FALSE, 'Rugby'),
(DEFAULT, 'Un turnover si près de la ligne d''en-but, ils vont s''en mordre les doigts !' , FALSE, 'Rugby'), 
(DEFAULT, 'Cadrage-Débor, chistera... Voilà un rugby champagne comme on les aime !' , TRUE, 'Rugby'),
(DEFAULT, 'Un placage dévastateur, à en faire rougir Thierry Dusautoir', TRUE, 'Rugby'),
(DEFAULT, 'Il n''a pas la tête au pré, ces yeux sont rivés sur les Pompom Girls' , FALSE, 'Rugby'),
(DEFAULT, 'Une fourchette ! Sanction immédiate, carton jaune et 10 minutes à 14 !',FALSE, 'Rugby'),
(DEFAULT, 'Voilà une superbe action, à montrer dans toutes les écoles de Rugby' , TRUE, 'Rugby' ) ,
(DEFAULT, 'Fantastique course, il élimine trois adversaires et raffute le dernier pour applatir entre les poteaux, Superbe ! ' , TRUE, 'Rugby'),
(DEFAULT, 'Plaquage dangereux, cravate ! Il en perd son dentier, ça mérite sanction !', FALSE, 'Rugby' ) ,
(DEFAULT, 'Ce joueur a vraiment de génie, petit coup de pied par dessus, et c''est toute l''équipe qui avance !' , TRUE, 'Rugby'),
(DEFAULT, 'Enorme relais, à cette allure là, il va tous les faire craquer !', TRUE, 'Cyclisme'),
(DEFAULT, 'Laché dès les premiers hectomètres du col, ne serait-il qu''un porteur de bidon ?', FALSE, 'Cyclisme'),
(DEFAULT, 'Battu d''un boyau, cruelle désillusion pour ce sprinteur de talent...', FALSE, 'Cyclisme'),
(DEFAULT, 'Manque de confiance ou de talent, il affiche un piètre 1/8 à trois points !', FALSE , 'Basket-Ball'),
(DEFAULT, 'Il rate un nouveau shoot à mi-distance, dure soirée pour ce pivot !', FALSE , 'Basket-Ball'),
(DEFAULT, 'Un quart-temps moyen, il faut se reprendre au plus vite !', FALSE , 'Basket-Ball'),
(DEFAULT, 'Une fringale au pire moment et c''est la victoire qui s''envole !', FALSE , 'Cyclisme'),
(DEFAULT, 'Il bascule au sommet du col avec les meilleurs, bel exploit pour ce jeune grimpeur !', TRUE , 'Cyclisme'),
(DEFAULT, 'Un nouveau revers manqué... Il n''est pas dans un grand jour !', FALSE , 'Tennis' ) ,
(DEFAULT, 'Totalement dépassé ! Rien à faire sur cette accélération de revers... ', FALSE , 'Tennis' ) ,
(DEFAULT, 'Nouvelle faute directe... Il semble craquer... ', FALSE , 'Tennis' ) ,
(DEFAULT, 'Il appelle le kiné, c''est mauvais signe ! Un abandon en perspective ?', FALSE , 'Tennis' ) ,
(DEFAULT, 'Après un combat du fond du court, il craque... Manque de souffle ou de talent ?', FALSE , 'Tennis' ) ,
(DEFAULT, 'Et voilà qu''il explose littéralement sa raquette ! Avertissement, il faut se reprendre !', FALSE , 'Tennis' ) ,
(DEFAULT, '"Out !" confirmé par le Eye-Hawk. Sale journée pour ce joueur en perdition...', FALSE , 'Tennis' );






----------------------------------------------------------------------------- UPDATE 1


DROP TYPE IF EXISTS score_mode CASCADE;
CREATE TYPE score_mode AS ENUM ('Normal','DefisDimanche','BonusDefisDimanche');

ALTER TABLE "scores" ADD COLUMN "score_mode" score_mode NOT NULL DEFAULT 'Normal';


DROP TABLE IF EXISTS defis_dimanche CASCADE;
CREATE TABLE defis_dimanche ( id SERIAL PRIMARY KEY,
							 id_account_1 INTEGER NOT NULL REFERENCES Accounts(id),
							 id_account_2 INTEGER REFERENCES Accounts(id),
							 id_questionnaire INTEGER NOT NULL REFERENCES Questionnaires(id), 
							 sport sport NOT NULL,
							 id_score INTEGER NOT NULL REFERENCES Scores(id),
							 id_winner INTEGER REFERENCES Accounts(id));
